{
 "title": "Camel Counters",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Session Starts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "camelStatsChargingSessionStartCount"
    }
   ]
  },
  {
   "title": "Session Ends",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "camelStatsChargingSessionEndCount"
    }
   ]
  },
  {
   "title": "Session Error",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "camelStatsChargingSessionErrorCount"
    }
   ]
  }
 ]
}