{
 "title": "Database",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "engine 1 status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysPeerClusterClusterState{instance=\"proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysPeerClusterEngineId=\"1\",sysPeerClusterClusterId=\"1\"}",
     "legendFormat": "engine 1"
    }
   ]
  },
  {
   "title": "engine 2 status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysPeerClusterClusterState{instance=\"proc-s1e1-0.attmdev.svc.cluster.local:14700\", job=\"matrixx_mib\", sysPeerClusterEngineId=\"2\",sysPeerClusterClusterId=\"1\"}",
     "legendFormat": "engine 1"
    }
   ]
  },
  {
   "title": "subscribers count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "txnDatabaseObjectCount{instance=\"proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"1\"}",
     "legendFormat": "rec-proc101"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"1\"}",
     "legendFormat": "rec-proc102"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"publ-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"1\"}",
     "legendFormat": "rec-publ101"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"publ-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"1\"}",
     "legendFormat": "rec-publ102"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"ckpt-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"1\"}",
     "legendFormat": "rec-check101"
    }
   ]
  },
  {
   "title": "group count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "txnDatabaseObjectCount{instance=\"proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"4\"}",
     "legendFormat": "rec-proc101"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"4\"}",
     "legendFormat": "rec-proc102"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"publ-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"4\"}",
     "legendFormat": "rec-publ101"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"publ-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"4\"}",
     "legendFormat": "rec-publ102"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"publ-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"4\"}",
     "legendFormat": "rec-check101"
    }
   ]
  },
  {
   "title": "subscribers count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "txnDatabaseObjectCount{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"1\"}",
     "legendFormat": "mtb-proc101"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"publ-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"1\"}",
     "legendFormat": "mtb-publ101"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"ckpt-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"1\"}",
     "legendFormat": "mtb-check101"
    }
   ]
  },
  {
   "title": "group count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "txnDatabaseObjectCount{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"4\"}",
     "legendFormat": "mtb-proc101"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"MTB-TRF-PROC102:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"4\"}",
     "legendFormat": "mtb-proc102"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"MTB-TRF-PUBL101:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"4\"}",
     "legendFormat": "mtb-publ101"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"MTB-TRF-PUBL102:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"4\"}",
     "legendFormat": "mtb-publ102"
    },
    {
     "expr": "txnDatabaseObjectCount{instance=\"MTB-TRF-CHECK101:14700\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"4\"}",
     "legendFormat": "mtb-check101"
    }
   ]
  },
  {
   "title": "sub (all) memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DatabaseMemoryUsedKb{instance=\"proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\"}",
     "legendFormat": "rec-proc101"
    },
    {
     "expr": "txnDatabaseMemoryUsedKb{instance=\"tralb-publ-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\"}",
     "legendFormat": "rec-publ101"
    },
    {
     "expr": "txnDatabaseMemoryUsedKb{instance=\"ckpt-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\"}",
     "legendFormat": "rec-check101"
    }
   ]
  },
  {
   "title": "sub (all) memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "txnDatabaseMemoryUsedKb{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\"}",
     "legendFormat": "mtb-proc101"
    },
    {
     "expr": "txnDatabaseMemoryUsedKb{instance=\"publ-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\"}",
     "legendFormat": "mtb-publ102"
    },
    {
     "expr": "txnDatabaseMemoryUsedKb{instance=\"ckpt-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\"}",
     "legendFormat": "mtb-check101"
    }
   ]
  }
 ]
}