{
 "title": "MATRIXX Subdomain Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Subdomain", "label": "Subdomain", "query": "label_values(subdomain)" }
  ]
 },
 "panels": [
  {
   "title": "ActiveMQ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_Active"
    }
   ]
  },
  {
   "title": "Camel Notifier",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "camelStatsChargingSessionStartCount"
    }
   ]
  },
  {
   "title": "RSGateway Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(tomcat_sessions_active_current_sessions{application=\"rsgateway\",} * 100 ) / tomcat_sessions_active_max_sessions{application=\"rsgateway\",}"
    }
   ]
  },
  {
   "title": "IMDB memory used (KB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "txnDatabaseMemoryUsedKb{instance=\"proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} * 100 /(\ntxnDatabaseMemoryUsedKb{instance=\"proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} + txnDatabaseMemoryFreeKb{instance=\"proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"})",
     "legendFormat": "proc101"
    },
    {
     "expr": "txnDatabaseMemoryUsedKb{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} * 100 /(\ntxnDatabaseMemoryUsedKb{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} +\ntxnDatabaseMemoryFreeKb{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"})",
     "legendFormat": "proc102"
    },
    {
     "expr": "txnDatabaseMemoryUsedKb{instance=\"tralb-publ-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} * 100 / (\ntxnDatabaseMemoryUsedKb{instance=\"tralb-publ-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} + \ntxnDatabaseMemoryFreeKb{instance=\"tralb-publ-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"})",
     "legendFormat": "publ101"
    },
    {
     "expr": "txnDatabaseMemoryUsedKb{instance=\"tralb-publ-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} * 100 / (\ntxnDatabaseMemoryUsedKb{instance=\"tralb-publ-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} + \ntxnDatabaseMemoryFreeKb{instance=\"tralb-publ-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"})",
     "legendFormat": "publ102"
    },
    {
     "expr": "(txnDatabaseMemoryUsedKb{instance=\"ckpt-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} * 100 ) /\n(txnDatabaseMemoryUsedKb{instance=\"ckpt-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} + \ntxnDatabaseMemoryFreeKb{instance=\"ckpt-s1e1.matrixx-prod-int.svc.cluster.local:14700\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"})",
     "legendFormat": "check101"
    }
   ]
  },
  {
   "title": "MongoDB RS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mongodb_up" }
   ]
  },
  { "title": "NGINX", "type": "stat", "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  {
   "title": "Tra Disaster Recovery",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysTraNodeState{instance=\"tra-rt-ag1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_tra_mib\",subdomain=\"subdomain-1\"}",
     "legendFormat": "e1 tradr 1"
    },
    {
     "expr": "sysTraNodeState{instance=\"tra-rt-ag1-1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_tra_mib\",subdomain=\"subdomain-1\"}",
     "legendFormat": "e1 tradr 2"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 20, "x": 0, "y": 4 }, "options": { "content": "Engine 1\n         " } },
  { "type": "text", "gridPos": { "h": 1, "w": 4, "x": 20, "y": 4 }, "options": { "content": "Subdomain errors" } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysPeerClusterClusterState{instance=\"proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysPeerClusterEngineId=\"1\",sysPeerClusterClusterId=\"1\",subdomain=\"$Subdomain\"}",
     "legendFormat": "engine 1"
    }
   ]
  },
  {
   "title": "Blades",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysClusterMemberNodeState{instance=\"proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\",subdomain=\"$Subdomain\"}",
     "legendFormat": "processing 1"
    },
    {
     "expr": "sysClusterMemberNodeState{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "processing 2"
    },
    {
     "expr": "sysClusterMemberNodeState{instance=\"publ-s1e1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\",subdomain=\"$Subdomain\"}",
     "legendFormat": "publishing 1"
    },
    {
     "expr": "sysClusterMemberNodeState{instance=\"publ-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "publishing 2"
    },
    {
     "expr": "sysClusterMemberNodeState{instance=\"ckpt-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\",subdomain=\"$Subdomain\"}",
     "legendFormat": "checkpoint 1"
    }
   ]
  },
  {
   "title": "Tra Load Balancer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysTraNodeState{instance=\"tralb-proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\",job=\"matrixx_tra_mib\",subdomain=\"$Subdomain\"}",
     "legendFormat": "tralb-pub 1"
    },
    {
     "expr": "sysTraNodeState{instance=\"tralb-publ-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",job=\"matrixx_tra_mib\",subdomain=\"$Subdomain\"}",
     "legendFormat": "tralb-pub 2"
    }
   ]
  },
  {
   "title": "Proc Errors",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(name)(sysProcessingErrors{subdomain=\"${Subdomain}\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 20, "x": 0, "y": 9 }, "options": { "content": "Engine 2\n         " } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysPeerClusterClusterState{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysPeerClusterEngineId=\"2\",sysPeerClusterClusterId=\"1\",subdomain=\"$Subdomain\"}",
     "legendFormat": "engine 2"
    }
   ]
  },
  {
   "title": "Blades",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysClusterMemberNodeState{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "processing 1"
    },
    {
     "expr": "sysClusterMemberNodeState{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"2\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "processing 2"
    },
    {
     "expr": "sysClusterMemberNodeState{instance=\"publ-s1e1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "publishing 1"
    },
    {
     "expr": "sysClusterMemberNodeState{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"2\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "publishing 2"
    },
    {
     "expr": "sysClusterMemberNodeState{instance=\"ckpt-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "checkpoint 1"
    }
   ]
  },
  {
   "title": "Tra Load Balancer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysTraNodeState{instance=\"tralb-proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\",job=\"matrixx_tra_mib\",subdomain=\"subdomain-1\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "tralb-pub 1"
    },
    {
     "expr": "sysTraNodeState{instance=\"tralb-publ-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",job=\"matrixx_tra_mib\",subdomain=\"subdomain-1\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "tralb-pub 2"
    }
   ]
  }
 ]
}