{
 "title": "MongoDB v2",
 "description": "MongoDB Prometheus Exporter Dashboard. A fork inspired from https://grafana.com/grafana/dashboards/2583 which is made to work well with https://github.com/percona/mongodb_exporter.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": "label_values(mongodb_connections{state=\"available\"}, kubernetes_pod_name)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "set",
    "label": "set",
    "query": "label_values(mongodb_mongod_replset_my_name, set)"
   }
  ]
 },
 "panels": [
  { "title": "Replica Set Status for $set", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "set" },
  {
   "title": "Member Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{set=~\"$set\"}",
     "legendFormat": "# members"
    },
    {
     "expr": "count(mongodb_mongod_replset_member_state{set=~\"$set\",state!=\"(not reachable/healthy)\"})",
     "legendFormat": "healthy members"
    },
    {
     "expr": "count(mongodb_mongod_replset_member_state{set=~\"$set\", state=\"(not reachable/healthy)\"})",
     "legendFormat": "not healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "stat",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_state{set=~\"$set\"}",
     "legendFormat": "{{state}} - {{name}}"
    }
   ]
  },
  {
   "title": "UP Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_uptime{set=\"$set\"}",
     "legendFormat": "{{set}}{{state}}"
    }
   ]
  },
  { "title": "Replica Set Status for $set", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Member Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{set=~\"$set\"}",
     "legendFormat": "# members"
    },
    {
     "expr": "count(mongodb_mongod_replset_member_state{set=~\"$set\",state!=\"(not reachable/healthy)\"})",
     "legendFormat": "healthy members"
    },
    {
     "expr": "count(mongodb_mongod_replset_member_state{set=~\"$set\", state=\"(not reachable/healthy)\"})",
     "legendFormat": "not healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "stat",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_state{set=~\"$set\"}",
     "legendFormat": "{{state}} - {{name}}"
    }
   ]
  },
  {
   "title": "UP Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_uptime{set=\"$set\"}",
     "legendFormat": "{{set}}{{state}}"
    }
   ]
  },
  { "title": "Replica Set Status for $set", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Member Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{set=~\"$set\"}",
     "legendFormat": "# members"
    },
    {
     "expr": "count(mongodb_mongod_replset_member_state{set=~\"$set\",state!=\"(not reachable/healthy)\"})",
     "legendFormat": "healthy members"
    },
    {
     "expr": "count(mongodb_mongod_replset_member_state{set=~\"$set\", state=\"(not reachable/healthy)\"})",
     "legendFormat": "not healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "stat",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_state{set=~\"$set\"}",
     "legendFormat": "{{state}} - {{name}}"
    }
   ]
  },
  {
   "title": "UP Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_uptime{set=\"$set\"}",
     "legendFormat": "{{set}}{{state}}"
    }
   ]
  },
  { "title": "Replica Set Status for $set", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Member Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{set=~\"$set\"}",
     "legendFormat": "# members"
    },
    {
     "expr": "count(mongodb_mongod_replset_member_state{set=~\"$set\",state!=\"(not reachable/healthy)\"})",
     "legendFormat": "healthy members"
    },
    {
     "expr": "count(mongodb_mongod_replset_member_state{set=~\"$set\", state=\"(not reachable/healthy)\"})",
     "legendFormat": "not healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "stat",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_state{set=~\"$set\"}",
     "legendFormat": "{{state}} - {{name}}"
    }
   ]
  },
  {
   "title": "UP Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_uptime{set=\"$set\"}",
     "legendFormat": "{{set}}{{state}}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Replica Query Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(mongodb_op_counters_repl_total{}[$interval]), \"slabel\",\"$1\",\"kubernetes_pod_name\",\"mongo-exporter-(shard-[1-9])-.*\")",
     "legendFormat": "{{slabel}}:{{type}}"
    }
   ]
  },
  {
   "title": "Oplog Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(mongodb_mongod_replset_oplog_size_bytes{}, \"slabel\",\"$1\",\"kubernetes_pod_name\",\"mongo-exporter-(shard-[1-9])-.*\")",
     "legendFormat": "{{slabel}}:{{type}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "label_replace(mongodb_memory{type=~\"resident|virtual\"}, \"slabel\",\"$1\",\"kubernetes_pod_name\",\"mongo-exporter-(shard-[1-9])-.*\")",
     "legendFormat": "{{slabel}}:{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(mongodb_network_bytes_total{}[$interval]), \"slabel\",\"$1\",\"kubernetes_pod_name\",\"mongo-exporter-(shard-[1-9])-.*\")",
     "legendFormat": "{{slabel}}:{{state}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oplog Lag",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(mongodb_mongod_replset_oplog_head_timestamp[5m]), \"slabel\",\"$1\",\"kubernetes_pod_name\",\"mongo-exporter-(shard-[1-9])-.*\")",
       "legendFormat": "{{slabel}}"
      }
     ]
    },
    {
     "title": "Disk IO Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_io_time_seconds_total[5m])/1000 or irate(node_disk_io_time_seconds_total[5m])/1000)",
       "legendFormat": "{{device}} - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}