{
 "title": "Network Enabler",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "signallingNetworkState{job=\"matrixx_ne_mib\"}",
     "legendFormat": "Signal: {{signallingNetworkLinkId}}"
    }
   ]
  },
  {
   "title": "Payload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(signallingNetworkPayloadDataReceivedCount{instance=\"10.150.152.233:14700\",job=\"matrixx_ne_mib\"}[5m])",
     "legendFormat": "SID {{signallingNetworkLinkId}} Received"
    },
    {
     "expr": "rate(signallingNetworkPayloadDataSentCount{instance=\"10.150.152.233:14700\",job=\"matrixx_ne_mib\"}[5m])",
     "legendFormat": "SID {{signallingNetworkLinkId}} Sent"
    }
   ]
  },
  {
   "title": "SSCP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(signallingNetworkReceivedDeliveryErrorCount{job=\"matrixx_ne_mib\"}[5m])",
     "legendFormat": "SID {{signallingNetworkLinkId}} ReceivedDeliveryErrorCount"
    },
    {
     "expr": "rate(signallingNetworkReceivedRateLimitCount{job=\"matrixx_ne_mib\"}[5m])",
     "legendFormat": "SID {{signallingNetworkLinkId}} ReceivedRateLimitCount"
    }
   ]
  },
  {
   "title": "UDT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(signallingNetworkUDTReceivedCount{instance=\"10.150.152.233:14700\",job=\"matrixx_ne_mib\"}[5m])",
     "legendFormat": "SID {{signallingNetworkLinkId}} Received"
    },
    {
     "expr": "rate(signallingNetworkUDTSentCount{instance=\"10.150.152.233:14700\",job=\"matrixx_ne_mib\"}[5m])",
     "legendFormat": "SID {{signallingNetworkLinkId}} Sent"
    }
   ]
  },
  {
   "title": "UDTS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(signallingNetworkUDTSReceivedCount{instance=\"10.150.152.233:14700\",job=\"matrixx_ne_mib\"}[5m])",
     "legendFormat": "SID {{signallingNetworkLinkId}} Received"
    },
    {
     "expr": "rate(signallingNetworkUDTSSentCount{instance=\"10.150.152.233:14700\",job=\"matrixx_ne_mib\"}[5m])",
     "legendFormat": "SID {{signallingNetworkLinkId}} Sent"
    }
   ]
  },
  {
   "title": "XUDT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(signallingNetworkXUDTReceivedCount{instance=\"10.150.152.233:14700\",job=\"matrixx_ne_mib\"}[5m])",
     "legendFormat": "SID {{signallingNetworkLinkId}} Received"
    },
    {
     "expr": "rate(signallingNetworkXUDTSentCount{instance=\"10.150.152.233:14700\",job=\"matrixx_ne_mib\"}[5m])",
     "legendFormat": "SID {{signallingNetworkLinkId}} Sent"
    }
   ]
  },
  {
   "title": "XUDTS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(signallingNetworkXUDTSReceivedCount{instance=\"10.150.152.233:14700\",job=\"matrixx_ne_mib\"}[5m])",
     "legendFormat": "SID {{signallingNetworkLinkId}} Received"
    },
    {
     "expr": "rate(signallingNetworkXUDTSSentCount{instance=\"10.150.152.233:14700\",job=\"matrixx_ne_mib\"}[5m])",
     "legendFormat": "SID {{signallingNetworkLinkId}} Sent"
    }
   ]
  }
 ]
}