{
 "title": "Processing Errors Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Subdomain", "label": "Subdomain", "query": "label_values(subdomain)" }
  ]
 },
 "panels": [
  {
   "title": "SYS Processing Errors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(name)(sysProcessingErrors{subdomain=\"${Subdomain}\"})"
    }
   ]
  },
  {
   "title": "Proc Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysProcessingErrors{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_common_mib\", subdomain=\"${Subdomain}\"}",
     "legendFormat": "proc-s1e1-0"
    },
    {
     "expr": "sysProcessingErrors{instance=\"proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_common_mib\", subdomain=\"${Subdomain}\"}",
     "legendFormat": "proc-s1e1"
    }
   ]
  },
  {
   "title": "Publ Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysProcessingErrors{instance=\"publ-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_common_mib\", subdomain=\"${Subdomain}\"}",
     "legendFormat": "publ-s1e1-0"
    },
    {
     "expr": "sysProcessingErrors{instance=\"publ-s1e1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_common_mib\", subdomain=\"${Subdomain}\"}",
     "legendFormat": "publ-s1e1"
    }
   ]
  },
  {
   "title": "Ckpt Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysProcessingErrors{instance=\"ckpt-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_common_mib\", subdomain=\"${Subdomain}\"}",
     "legendFormat": "ckpt-s1e1-0"
    },
    {
     "expr": "sysProcessingErrors{instance=\"ckpt-s1e1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_common_mib\", subdomain=\"${Subdomain}\"}",
     "legendFormat": "ckpt-s1e1"
    }
   ]
  },
  {
   "title": "Tralb Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysProcessingErrors{instance=\"tralb-proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_common_mib\", subdomain=\"${Subdomain}\"}",
     "legendFormat": "tralb-proc-s1e1-0"
    },
    {
     "expr": "sysProcessingErrors{instance=\"tralb-proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_common_mib\", subdomain=\"${Subdomain}\"}",
     "legendFormat": "tralb-proc-ag1-1"
    },
    {
     "expr": "sysProcessingErrors{instance=\"tralb-publ-s1e1-ag1-1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_common_mib\", subdomain=\"${Subdomain}\"}"
    },
    {
     "expr": "sysProcessingErrors{instance=\"tralb-publ-s1e1-ag1-1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_common_mib\", subdomain=\"${Subdomain}\"}"
    }
   ]
  },
  {
   "title": "Trart ag Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysProcessingErrors{instance=\"tra-rt-ag1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_common_mib\", subdomain=\"${Subdomain}\"}",
     "legendFormat": "tra-rt-ag1-0"
    },
    {
     "expr": "sysProcessingErrors{instance=\"tra-rt-ag1-1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_common_mib\", subdomain=\"${Subdomain}\"}",
     "legendFormat": "tra-rt-ag1-1"
    }
   ]
  }
 ]
}