apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        # image: mxtltppeharbor.mx.att.com/matrixx_prod01/monitoring/prom/alertmanager:v0.20.0
        # image: mxtltqpeharbor.mx.att.com/matrixx_prep01/monitoring/prom/alertmanager:v0.20.0
        image: mxtltppeharbor.mx.att.com/matrixx_prod01/monitoring/prom/alertmanager:v0.23.0
        args:
        - --config.file=/etc/alertmanager/alertmanager.yml
        # - --storage.path=/data
        - "--cluster.advertise-address=$(POD_IP):6783"
        # - "--web.external-url=/"
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        ports:
        - containerPort: 9093
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        # - mountPath: /var/lib/alertmanager
        #   name: data
        - name: config-volume
          mountPath: /etc/alertmanager
      imagePullSecrets:
        - name: regcred
      volumes:
      # - emptyDir: {}
      #   name: data
      - name: config-volume
        configMap:
          defaultMode: 420
          name: alertmanager-config