apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: infra-harbor-paas.attmx-ne.local/matrixx_lab01/prom/alertmanager:v0.20.0
        #args:
        # - "--config.file=/etc/alertmanager/config.yml"
        #  - "--storage.path=/alertmanager"
        ports:
        - containerPort: 9093
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/alertmanager
          name: data
        #- name: config-volume
        #  mountPath: /etc/alertmanager
        #- name: alertmanager
        #  mountPath: /alertmanager
      volumes:
      - emptyDir: {}
        name: data
      #- name: config-volume
      #  configMap:
      #    name: alertmanager-config
      #- name: alertmanager
      #  emptyDir: {}