kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
  
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'email'
    receivers:
    - name: 'email'
      email_configs:
      - to: 'israel.mayen@onissolutions.com'
        from: 'prepaid_evolution_alert@att.com.mx'
        smarthost: 135.208.35.1:25
        require_tls: false
      - to: 'martin.ortega@onissolutions.com'
        from: 'prepaid_evolution_alert@att.com.mx'
        smarthost: 135.208.35.1:25
        require_tls: false
      - to: 'edgar.lopez@onissolutions.com'
        from: 'prepaid_evolution_alert@att.com.mx'
        smarthost: 135.208.35.1:25
        require_tls: false
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']