kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
      email-configs:
      - to: to-email@example.com
      - from: from-email@example.com
        #Your smtp server
        smarthost: smtpi.mx.att.com:25
        auth_username: from
        auth_identify: from
        auth_password: 
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h