apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: grafana
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: grafana
    spec:
      containers:
      - image: mxtlpdmharbor.mx.att.com/matrixx_lab01/grafana/grafana:7.1.1
      #- image: mxtltppeharbor.mx.att.com/matrixx_prod01/monitoring/grafana/grafana:7.1.1
      #- image: infra-harbor-paas.attmx-ne.local/matrixx_lab01/grafana/grafana:7.1.1
        imagePullPolicy: IfNotPresent
        name: grafana
        # securityContext:
        #   fsGroup: 472
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - mountPath: /etc/grafana/provisioning/datasources/
          name: datasources
        - mountPath: /grafana-dashboard-definitions/0/statefulset
          name: grafana-dashboard-definitions
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      # hostAliases:
      # - ip: 10.150.152.190
      #   hostnames:
      #   - sigmadev-provisioning-prereq-pronetheus.attmx-ne.local
      securityContext:
        fsGroup: 472
      terminationGracePeriodSeconds: 30
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-storage
      - configMap:
          name: grafana-datasources
        name: datasources
      - configMap:
          name: grafana-dashboard-definitions
        name: grafana-dashboard-definitions
      - configMap:
          name: grafana-dashboards
        name: grafana-dashboards          
