apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: grafana
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: grafana
    spec:
      containers:
      #- image: infra-harbor-paas.attmx-ne.local/matrixx_lab01/grafana/grafana:6.5.3
      - image: mxtlpdmharbor.mx.att.com/matrixx_lab01/grafana/grafana:6.5.3
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: data
        - mountPath: /etc/grafana/provisioning/datasources/
          name: datasources
        - mountPath: /grafana-dashboard-definitions/0/statefulset
          name: grafana-dashboard-definitions
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
      - configMap:
          name: grafana-datasources
        name: datasources
      - configMap:
          name: grafana-dashboard-definitions
        name: grafana-dashboard-definitions
      - configMap:
          name: grafana-dashboards
        name: grafana-dashboards
