apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpbmZyYS1oYXJib3ItcGFhcy5hdHRteC1uZS5sb2NhbCI6eyJ1c2VybmFtZSI6ImRldmVsb3BlckBhdHRteC1uZS5sb2NhbCIsInBhc3N3b3JkIjoiRDNzNHJyMDExMCIsImVtYWlsIjoiZ3JhaGFtLmJlbnRvbkBtYXRyaXh4LmNvbSIsImF1dGgiOiJaR1YyWld4dmNHVnlRR0YwZEcxNExXNWxMbXh2WTJGc09rUXpjelJ5Y2pBeE1UQT0ifX19
kind: Secret
metadata:
  namespace: monitoring
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{".dockerconfigjson":"eyJhdXRocyI6eyJpbmZyYS1oYXJib3ItcGFhcy5hdHRteC1uZS5sb2NhbCI6eyJ1c2VybmFtZSI6ImRldmVsb3BlckBhdHRteC1uZS5sb2NhbCIsInBhc3N3b3JkIjoiRDNzNHJyMDExMCIsImVtYWlsIjoiZ3JhaGFtLmJlbnRvbkBtYXRyaXh4LmNvbSIsImF1dGgiOiJaR1YyWld4dmNHVnlRR0YwZEcxNExXNWxMbXh2WTJGc09rUXpjelJ5Y2pBeE1UQT0ifX19"},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":null,"name":"regcred","namespace":"monitoring","selfLink":"/api/v1/namespaces/attmdev/secrets/regcred"},"type":"kubernetes.io/dockerconfigjson"}
  creationTimestamp: null
  name: regcred
  selfLink: /api/v1/namespaces/monitoring/secrets/regcred
type: kubernetes.io/dockerconfigjson