{
 "title": "General Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "MATRIXX Env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Enabler",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "signallingNetworkState{job=\"matrixx_ne_mib\"}",
     "legendFormat": "NLID: {{signallingNetworkLinkId}}"
    }
   ]
  },
  {
   "title": "Subdomains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sysPeerClusterClusterState{instance=~\"proc-.*\", job=\"matrixx_mib\"}) / count( sysPeerClusterClusterState{instance=~\"proc-.*\", job=\"matrixx_mib\"} )",
     "legendFormat": "PROC"
    },
    {
     "expr": "sum(sysPeerClusterClusterState{instance=~\"publ-.*\", job=\"matrixx_mib\"}) / count( sysPeerClusterClusterState{instance=~\"publ-.*\", job=\"matrixx_mib\"} )",
     "legendFormat": "PUBL"
    },
    {
     "expr": "sum(sysPeerClusterClusterState{instance=~\"ckpt-.*\", job=\"matrixx_mib\"}) / count( sysPeerClusterClusterState{instance=~\"ckpt-.*\", job=\"matrixx_mib\"} )",
     "legendFormat": "CKPT"
    }
   ]
  },
  { "title": "VMWare", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Host Number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_host_connection_state)"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_cpu_usagemhz_average) * 100 / sum(vmware_host_cpu_max)"
    }
   ]
  },
  {
   "title": "Cluster Memory usage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_memory_usage) * 100 / sum(vmware_host_memory_max)"
    }
   ]
  },
  { "title": "K8 Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "MongoDB PODs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (kube_pod_info{namespace=\"mongodb\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Mon PODs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info {namespace=\"monitoring\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "MTTX PODs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info {namespace=\"mtx-attm-qa\"})",
     "legendFormat": "mtx-attm-qa"
    }
   ]
  },
  {
   "title": "Sigma PODs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info {namespace=\"sigmaqa\"})",
     "legendFormat": "sigmaqa"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod!=\"\"}) / sum (kube_node_status_allocatable_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total[2m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum(kube_deployment_status_replicas) or vector(0)) + (sum(kube_statefulset_replicas) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled) or vector(0))) - ((sum(kube_deployment_status_replicas_available) or vector(0)) + (sum(kube_statefulset_status_replicas) or vector(0)) + (sum(kube_daemonset_status_number_ready) or vector(0)))) / ((sum(kube_deployment_status_replicas) or vector(0)) + (sum(kube_statefulset_replicas) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled) or vector(0))) * 100"
    }
   ]
  },
  { "title": "Hansen Environment / MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "Order Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(irate(om_order_from_create_seconds_sum{state=\"closed.completed.all\"}[2m])*1000/irate(om_order_from_create_seconds_count{state=\"closed.completed.all\"}[2m])) "
    }
   ]
  },
  {
   "title": "MongoDB ReplicaSet",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mongodb_up" }
   ]
  }
 ]
}