{
 "title": "MATRIXX Subdomain Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Subdomain", "label": "Subdomain", "query": "label_values(subdomain)" }
  ]
 },
 "panels": [
  {
   "title": "ActiveMQ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_Active"
    }
   ]
  },
  {
   "title": "Camel Notifier",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "camelStatsChargingSessionStartCount"
    }
   ]
  },
  {
   "title": "RSGateway request duration (sec)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(mtx_web_request_proc_duration_seconds_sum{application=\"rsgateway\",exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/data/json/pricing/status\",} [5m])",
     "legendFormat": "mtx_web_req_proc"
    },
    {
     "expr": "rate(mtx_web_request_rtt_duration_seconds_sum{application=\"rsgateway\",exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/data/json/pricing/status\",}[5m])",
     "legendFormat": "mtx_web_req_rtt"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"rsgateway\",exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/data/json/pricing/status\",}[5m])",
     "legendFormat": "http_server_req"
    }
   ]
  },
  {
   "title": "IMDB memory used (KB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "txnDatabaseMemoryUsedKb{instance=~\"proc-.*\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} * 100 /(\ntxnDatabaseMemoryUsedKb{instance=~\"proc-.*\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} +\ntxnDatabaseMemoryFreeKb{instance=~\"proc-.*\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"})",
     "legendFormat": "Proc"
    },
    {
     "expr": "(txnDatabaseMemoryUsedKb{instance=~\"ckpt-.*\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} * 100 ) /\n(txnDatabaseMemoryUsedKb{instance=~\"ckpt-.*\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"} + \ntxnDatabaseMemoryFreeKb{instance=~\"ckpt-.*\",txnDatabasePoolId=\"5\",subdomain=\"$Subdomain\"})",
     "legendFormat": "Ckpt"
    }
   ]
  },
  {
   "title": "MongoDB RS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mongodb_up" }
   ]
  },
  { "title": "NGINX", "type": "stat", "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  {
   "title": "Tra Disaster Recovery",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysTraNodeState{instance=~\"tra-rt-.*\", job=\"matrixx_tra_mib\",subdomain=\"$Subdomain\"}",
     "legendFormat": "e1 tradr 1"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 16, "x": 0, "y": 4 }, "options": { "content": "Engine 1\n         " } },
  {
   "title": "IMDB subscribers count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txnDatabaseObjectCount{instance=~\"proc-.*\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"1\", subdomain=\"$Subdomain\"}",
     "legendFormat": "rec-proc101"
    }
   ]
  },
  {
   "title": "Blades",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sysClusterMemberNodeState{instance=~\"proc-.*\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\",subdomain=\"$Subdomain\"}) / count(sysClusterMemberNodeState{instance=~\"proc-.*\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\",subdomain=\"$Subdomain\"})",
     "legendFormat": "processing 1"
    },
    {
     "expr": "sum(sysClusterMemberNodeState{instance=~\"proc-.*\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"2\",subdomain=\"$Subdomain\"}) / count(sysClusterMemberNodeState{instance=~\"proc-.*\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"2\",subdomain=\"$Subdomain\"})",
     "legendFormat": "processing 2"
    },
    {
     "expr": "sum(sysClusterMemberNodeState{instance=~\"publ-.*\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\",subdomain=\"$Subdomain\"}) / count(sysClusterMemberNodeState{instance=~\"publ-.*\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\",subdomain=\"$Subdomain\"})",
     "legendFormat": "publishing 1"
    },
    {
     "expr": "sum(sysClusterMemberNodeState{instance=~\"publ-.*\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"2\",subdomain=\"$Subdomain\"}) / count(sysClusterMemberNodeState{instance=~\"publ-.*\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"2\",subdomain=\"$Subdomain\"})",
     "legendFormat": "publishing 2"
    },
    {
     "expr": "sum(sysClusterMemberNodeState{instance=~\"ckpt-.*\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\",subdomain=\"$Subdomain\"}) / count(sysClusterMemberNodeState{instance=~\"ckpt-.*\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\",subdomain=\"$Subdomain\"})",
     "legendFormat": "checkpoint 1"
    }
   ]
  },
  {
   "title": "Tra Load Balancer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysTraNodeState{instance=~\"tralb-proc.*\",job=\"matrixx_tra_mib\",subdomain=\"$Subdomain\"}",
     "legendFormat": "tralb-proc 1"
    },
    {
     "expr": "sysTraNodeState{instance=~\"tralb-publ.*\",job=\"matrixx_tra_mib\",subdomain=\"$Subdomain\"}",
     "legendFormat": "tralb-pub 2"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 16, "x": 0, "y": 9 }, "options": { "content": "Engine 2\n         " } },
  {
   "title": "IMDB group count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txnDatabaseObjectCount{instance=~\"proc.*\",txnDatabaseObjectPoolId=\"5\",txnDatabaseObjectTypeId=\"4\"}",
     "legendFormat": "rec-proc101"
    }
   ]
  },
  {
   "title": "Blades",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysClusterMemberNodeState{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "processing 1"
    },
    {
     "expr": "sysClusterMemberNodeState{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"2\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "processing 2"
    },
    {
     "expr": "sysClusterMemberNodeState{instance=\"publ-s1e1.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "publishing 1"
    },
    {
     "expr": "sysClusterMemberNodeState{instance=\"proc-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"2\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "publishing 2"
    },
    {
     "expr": "sysClusterMemberNodeState{instance=\"ckpt-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\", job=\"matrixx_mib\", sysClusterMemberNodeId=\"1\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "checkpoint 1"
    }
   ]
  },
  {
   "title": "Tra Load Balancer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysTraNodeState{instance=\"tralb-proc-s1e1.matrixx-prod-int.svc.cluster.local:14700\",job=\"matrixx_tra_mib\",subdomain=\"subdomain-1\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "tralb-pub 1"
    },
    {
     "expr": "sysTraNodeState{instance=\"tralb-publ-s1e1-0.matrixx-prod-int.svc.cluster.local:14700\",job=\"matrixx_tra_mib\",subdomain=\"subdomain-1\", sysPeerClusterEngineId=\"2\",subdomain=\"$Subdomain\"}",
     "legendFormat": "tralb-pub 2"
    }
   ]
  },
  {
   "title": "Proc Errors",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysProcessingErrors{subdomain=\"${Subdomain}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}