{
 "title": "RSGateway",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "method", "label": "method", "query": "DELETE, POST, GET, PUT" },
   { "name": "status", "label": "status", "query": "200, 404, 422, 503" },
   { "name": "exception", "label": "exception", "query": "IllegalStateException, None" },
   {
    "name": "uri",
    "label": "uri",
    "query": "/**, /actuator/health, /actuator/health/**, /actuator/metrics, /actuator/prometheus, /data/json, /data/json/cache/pricing/balance/, /data/json/cache/pricing/CatalogItem, /data/json/pricing/balances, /data/json/pricing/offers, /data/json/pricing/service_types, /data/json/pricing/status, /data/json/subscriber/, /data/json/subscription/, /data/template/get/, /data/v3, /data/v3/attmex/v1.0/subscription/, /data/v3/device/, /data/v3/device/query/ExternalId/, /data/v3/mtx_config, /data/v3/pricing/balance/, /data/v3/pricing/balances, /data/v3/pricing/billing_cycles, /data/v3/pricing/CatalogItem, /data/v3/pricing/CatalogItem/, /data/v3/pricing/event_types, /data/v3/pricing/lifecycle/device, /data/v3/pricing/lifecycle/group, /data/v3/pricing/lifecycle/subscriber, /data/v3/pricing/lifecycle/user, /data/v3/pricing/offers/, /data/v3/pricing/status, /data/v3/pricing/user_role, /data/v3/service/user, /data/v3/subscriber/, /data/v3/subscriber/query/ExternalId/, /data/v3/subscription/, /data/v3/user/, /rsgateway/, /rsgateway/actuator/health, /rsgateway/actuator/health/camel, /rsgateway/actuator/metrics, /rsgateway/actuator/prometheus, /rsgateway/css/bootstrap.min.css, /rsgateway/css/main_ui.css, /rsgateway/css/service_console.css, /rsgateway/data/json, /rsgateway/data/json/cache/pricing/balance/21017, /rsgateway/data/json/cache/pricing/balance/21018, /rsgateway/data/json/cache/pricing/balance/21019, /rsgateway/data/json/cache/pricing/balance/21020, /rsgateway/data/json/cache/pricing/balance/21021, /rsgateway/data/json/cache/pricing/balance/21036, /rsgateway/data/json/cache/pricing/balance/21038, /rsgateway/data/json/cache/pricing/balance/21039, /rsgateway/data/json/cache/pricing/balance/21044, /rsgateway/data/json/cache/pricing/balance/21045, /rsgateway/data/json/cache/pricing/balance/21046, /rsgateway/data/json/cache/pricing/balance/21049, /rsgateway/data/json/cache/pricing/balance/21050, /rsgateway/data/json/cache/pricing/balance/21052, /rsgateway/data/json/cache/pricing/balance/21053, /rsgateway/data/json/cache/pricing/balance/21054, /rsgateway/data/json/cache/pricing/balance/21056, /rsgateway/data/json/cache/pricing/balance/21057, /rsgateway/data/json/cache/pricing/balance/21058, /rsgateway/data/json/cache/pricing/balance/21059, /rsgateway/data/json/cache/pricing/CatalogItem, /rsgateway/data/json/pricing/balances, /rsgateway/data/json/pricing/offers, /rsgateway/data/json/pricing/service_types, /rsgateway/data/json/pricing/status, /rsgateway/data/json/subscriber/0:1:5:25/offers/19, /rsgateway/data/json/subscriber/0:1:5:25/offers/21, /rsgateway/data/json/subscriber/0:1:5:25/offers/23, /rsgateway/data/json/subscription/0:1:5:19, /rsgateway/data/json/subscription/0:1:5:25, /rsgateway/data/template/get/about.html, /rsgateway/data/template/get/NavigationTile.html, /rsgateway/data/v3, /rsgateway/data/v3/attmex/v1.0/subscription/AccessNumber+10/deposit, /rsgateway/data/v3/device/0-1-5-16, /rsgateway/data/v3/device/0-1-5-22, /rsgateway/data/v3/device/0-1-5-22/policycounter, /rsgateway/data/v3/device/0-1-5-22/session, /rsgateway/data/v3/device/0-1-5-28/policycounter, /rsgateway/data/v3/device/0-1-5-28/session, /rsgateway/data/v3/device/ObjectId+0-1-5-16, /rsgateway/data/v3/device/ObjectId+0-1-5-22, /rsgateway/data/v3/device/ObjectId+0-1-5-28, /rsgateway/data/v3/device/query/ExternalId/10, /rsgateway/data/v3/mtx_config, /rsgateway/data/v3/pricing/balance/21018, /rsgateway/data/v3/pricing/balance/21021, /rsgateway/data/v3/pricing/balances, /rsgateway/data/v3/pricing/billing_cycles, /rsgateway/data/v3/pricing/CatalogItem, /rsgateway/data/v3/pricing/CatalogItem/142, /rsgateway/data/v3/pricing/CatalogItem/143, /rsgateway/data/v3/pricing/CatalogItem/16, /rsgateway/data/v3/pricing/CatalogItem/185, /rsgateway/data/v3/pricing/CatalogItem/192, /rsgateway/data/v3/pricing/CatalogItem/193, /rsgateway/data/v3/pricing/CatalogItem/194, /rsgateway/data/v3/pricing/CatalogItem/197, /rsgateway/data/v3/pricing/CatalogItem/213, /rsgateway/data/v3/pricing/CatalogItem/214, /rsgateway/data/v3/pricing/CatalogItem/27, /rsgateway/data/v3/pricing/CatalogItem/73, /rsgateway/data/v3/pricing/event_types, /rsgateway/data/v3/pricing/lifecycle/device, /rsgateway/data/v3/pricing/lifecycle/group, /rsgateway/data/v3/pricing/lifecycle/subscriber, /rsgateway/data/v3/pricing/lifecycle/user, /rsgateway/data/v3/pricing/offers/, /rsgateway/data/v3/pricing/offers/106, /rsgateway/data/v3/pricing/offers/119, /rsgateway/data/v3/pricing/offers/120, /rsgateway/data/v3/pricing/offers/121, /rsgateway/data/v3/pricing/offers/122, /rsgateway/data/v3/pricing/offers/123, /rsgateway/data/v3/pricing/offers/124, /rsgateway/data/v3/pricing/offers/15, /rsgateway/data/v3/pricing/offers/16, /rsgateway/data/v3/pricing/offers/17, /rsgateway/data/v3/pricing/offers/18, /rsgateway/data/v3/pricing/offers/19, /rsgateway/data/v3/pricing/offers/20, /rsgateway/data/v3/pricing/offers/21, /rsgateway/data/v3/pricing/offers/41, /rsgateway/data/v3/pricing/offers/42, /rsgateway/data/v3/pricing/offers/43, /rsgateway/data/v3/pricing/offers/63, /rsgateway/data/v3/pricing/offers/93, /rsgateway/data/v3/pricing/offers/94, /rsgateway/data/v3/pricing/status, /rsgateway/data/v3/pricing/user_role, /rsgateway/data/v3/service/user, /rsgateway/data/v3/subscriber/0-1-5-13/device/0-1-5-16, /rsgateway/data/v3/subscriber/0-1-5-19/device/0-1-5-22, /rsgateway/data/v3/subscriber/0-1-5-19/payment_method, /rsgateway/data/v3/subscriber/0-1-5-19/wallet, /rsgateway/data/v3/subscriber/0-1-5-19/wallet/2/adjustment, /rsgateway/data/v3/subscriber/0-1-5-25/payment_method, /rsgateway/data/v3/subscriber/0-1-5-25/wallet, /rsgateway/data/v3/subscriber/0-1-5-25/wallet/10/adjustment, /rsgateway/data/v3/subscriber/0-1-5-25/wallet/11/adjustment, /rsgateway/data/v3/subscriber/0-1-5-25/wallet/9/adjustment, /rsgateway/data/v3/subscriber/query/ExternalId/10, /rsgateway/data/v3/subscription/0-1-5-13, /rsgateway/data/v3/subscription/0-1-5-19, /rsgateway/data/v3/subscription/0-1-5-19/offers, /rsgateway/data/v3/subscription/0-1-5-25, /rsgateway/data/v3/subscription/0-1-5-25/offers, /rsgateway/data/v3/subscription/ExternalId+10, /rsgateway/data/v3/subscription/ObjectId+0-1-5-13, /rsgateway/data/v3/subscription/ObjectId+0-1-5-19, /rsgateway/data/v3/user/0-1-5-12, /rsgateway/data/v3/user/0-1-5-12/subscription/0-1-5-13, /rsgateway/data/v3/user/0-1-5-18, /rsgateway/data/v3/user/0-1-5-18/subscription/0-1-5-19, /rsgateway/data/v3/user/ExternalId+2000010, /rsgateway/data/v3/user/ObjectId+0-1-5-12, /rsgateway/data/v3/user/ObjectId+0-1-5-18, /rsgateway/data/v3/user/UserId+2000010, /rsgateway/images/logo.jpg, /rsgateway/images/serviceconsole.png, /rsgateway/images/wait.gif, /rsgateway/index.js, /rsgateway/js/commonFunctions.js, /rsgateway/js/externalDialog.js, /rsgateway/js/fieldPicker.js, /rsgateway/js/navTiles.js, /rsgateway/jslib/bootstrap.min.js, /rsgateway/jslib/jquery-2.1.4.min.js, /rsgateway/jslib/jquery-migrate-1.2.1.min.js, /rsgateway/jslib/jquery-ui.js, /rsgateway/jslib/matrixx-1.0.0.js, /rsgateway/jslib/matrixx.accessController-1.0.0.js, /rsgateway/jslib/matrixx.json.nodevisitor-1.0.0.js, /rsgateway/jslib/matrixx.json.propsetter-1.0.0.js, /rsgateway/jslib/matrixx.jsonHandler-1.0.0.js"
   },
   {
    "name": "outcome",
    "label": "outcome",
    "query": "SUCCESS, CLIENT_ERROR, SERVER_ERROR"
   },
   { "name": "type", "label": "type", "query": "sum, count, max" }
  ]
 },
 "panels": [
  {
   "title": "JVM heap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jvm_memory_used_bytes{application=\"rsgateway\",area=\"heap\",id=\"Survivor Space\",} *  100) /jvm_memory_max_bytes{application=\"rsgateway\",area=\"heap\",id=\"Survivor Space\",}",
     "legendFormat": "Survivor Space"
    },
    {
     "expr": "(jvm_memory_used_bytes{application=\"rsgateway\",area=\"heap\",id=\"Eden Space\",} * 100) / jvm_memory_max_bytes{application=\"rsgateway\",area=\"heap\",id=\"Eden Space\",} ",
     "legendFormat": "Eden Space"
    },
    {
     "expr": "(jvm_memory_used_bytes{application=\"rsgateway\",area=\"heap\",id=\"Tenured Gen\",} * 100) /jvm_memory_max_bytes{application=\"rsgateway\",area=\"heap\",id=\"Tenured Gen\",}",
     "legendFormat": "Tenured Gen"
    }
   ]
  },
  {
   "title": "JVM nonheap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jvm_memory_used_bytes{application=\"rsgateway\",area=\"nonheap\",id=\"CodeHeap 'non-nmethods'\",} * 100) / jvm_memory_max_bytes{application=\"rsgateway\",area=\"nonheap\",id=\"CodeHeap 'non-nmethods'\",}",
     "legendFormat": "non-nmethods"
    },
    {
     "expr": "(jvm_memory_used_bytes{application=\"rsgateway\",area=\"nonheap\",id=\"CodeHeap 'non-profiled nmethods'\",} * 100 ) / \njvm_memory_max_bytes{application=\"rsgateway\",area=\"nonheap\",id=\"CodeHeap 'non-profiled nmethods'\",}",
     "legendFormat": "non-profiled nmethods"
    },
    {
     "expr": "(jvm_memory_used_bytes{application=\"rsgateway\",area=\"nonheap\",id=\"CodeHeap 'profiled nmethods'\",}*100) /jvm_memory_max_bytes{application=\"rsgateway\",area=\"nonheap\",id=\"CodeHeap 'profiled nmethods'\",}",
     "legendFormat": "Profiled nmethods"
    },
    {
     "expr": "(jvm_memory_used_bytes{application=\"rsgateway\",area=\"nonheap\",id=\"Compressed Class Space\",} * 100)/jvm_memory_max_bytes{application=\"rsgateway\",area=\"nonheap\",id=\"Compressed Class Space\",}",
     "legendFormat": "Compressed Class Space"
    }
   ]
  },
  {
   "title": "mtx_web_request_http_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mtx_web_request_http_duration_seconds_${type}{application=\"rsgateway\",exception=\"${exception}\",method=\"${method}\",status=\"${status}\",outcome=\"${outcome}\",uri=\"${uri}\",}",
     "legendFormat": "mtx_web_request_http_duration_seconds"
    }
   ]
  },
  {
   "title": "mtx_web_request_rtt_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mtx_web_request_rtt_duration_seconds_${type}{application=\"rsgateway\",exception=\"${exception}\",method=\"${method}\",status=\"${status}\",outcome=\"${outcome}\",uri=\"${uri}\",}",
     "legendFormat": "mtx_web_request_rtt_duration_seconds"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_${type}{application=\"rsgateway\",exception=\"${exception}\",method=\"${method}\",status=\"${status}\",outcome=\"${outcome}\",uri=\"${uri}\",}",
     "legendFormat": "http_server_requests_seconds"
    }
   ]
  },
  {
   "title": "mtx_web_request_proc_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mtx_web_request_proc_duration_seconds_${type}{application=\"rsgateway\",exception=\"${exception}\",method=\"${method}\",status=\"${status}\",outcome=\"${outcome}\",uri=\"${uri}\",}",
     "legendFormat": "mtx_web_request_proc_duration_seconds"
    }
   ]
  },
  {
   "title": "Log4J",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "log4j2_events_total{application=\"rsgateway\",level=\"debug\",}",
     "legendFormat": "debug"
    },
    {
     "expr": "log4j2_events_total{application=\"rsgateway\",level=\"error\",}",
     "legendFormat": "error"
    },
    {
     "expr": "log4j2_events_total{application=\"rsgateway\",level=\"fatal\",}",
     "legendFormat": "fatal"
    },
    {
     "expr": "log4j2_events_total{application=\"rsgateway\",level=\"trace\",}",
     "legendFormat": "trace"
    },
    {
     "expr": "log4j2_events_total{application=\"rsgateway\",level=\"warn\",}",
     "legendFormat": "warn"
    },
    {
     "expr": "log4j2_events_total{application=\"rsgateway\",level=\"info\",}",
     "legendFormat": "Info"
    }
   ]
  }
 ]
}