{
 "title": "Hansen Provision - Application Summary",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Order Processing Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Order Processing rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Orders" }
   ],
   "targets": [
    {
     "expr": "sum(irate(om_order_start_counter_total[2m]))",
     "legendFormat": "OM Order Processing rate"
    },
    {
     "expr": "sum(irate(wf_stream_input_requests_total[2m]))",
     "legendFormat": "WF Req Processing rate"
    }
   ]
  },
  {
   "title": "Order Completion Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "sum(irate(om_order_from_create_seconds_count[2m])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Order Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "avg(irate(om_order_from_create_seconds_sum{state=\"closed.completed.all\"}[2m])*1000/irate(om_order_from_create_seconds_count{state=\"closed.completed.all\"}[2m])) ",
     "legendFormat": "OM Order Duration"
    },
    {
     "expr": "avg(irate(wf_stream_completed_requests_millis_total[2m])) / avg(irate(wf_stream_completed_requests_count_total[2m]))",
     "legendFormat": "WF Req Duration"
    }
   ]
  },
  { "title": "Runtime Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "OM Input Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(om_order_start_counter_total[2m]))"
    }
   ]
  },
  {
   "title": "WF Input Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(wf_stream_input_requests_total[2m]))"
    }
   ]
  },
  {
   "title": "WF Duration",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(irate(wf_stream_completed_requests_millis_total[2m])) / avg(irate(wf_stream_completed_requests_count_total[2m]))/1000"
    }
   ]
  },
  {
   "title": "Order Duration",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(irate(om_order_from_create_seconds_sum{state=\"closed.completed.all\"}[2m])*1000/irate(om_order_from_create_seconds_count{state=\"closed.completed.all\"}[2m]))/1000 "
    }
   ]
  },
  {
   "title": "Triggered Alerts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  { "title": "Resource Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\", reservation!=\"monitoring\"}) / sum(kube_node_status_allocatable_memory_bytes{}  * on(node) group_left() kube_node_labels{label_reservation!=\"monitoring\"}) * 100"
    }
   ]
  },
  {
   "title": "Total CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\", reservation!=\"monitoring\"}[2m])) / sum (machine_cpu_cores{reservation!=\"monitoring\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/sdc1$\",id=\"/\", reservation!=\"monitoring\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/sdc1$\",id=\"/\", reservation!=\"monitoring\"}) * 100"
    },
    {}
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((sum(kube_deployment_status_replicas) or vector(0)) + (sum(kube_statefulset_replicas) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled) or vector(0))) - ((sum(kube_deployment_status_replicas_available) or vector(0)) + (sum(kube_statefulset_status_replicas) or vector(0)) + (sum(kube_daemonset_status_number_ready) or vector(0)))) / ((sum(kube_deployment_status_replicas) or vector(0)) + (sum(kube_statefulset_replicas) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled) or vector(0))) * 100"
    }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas_available) or vector(0)) + (sum(kube_statefulset_status_replicas) or vector(0)) + (sum(kube_daemonset_status_number_ready) or vector(0))"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas) or vector(0)) + (sum(kube_statefulset_status_replicas) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled) or vector(0))",
     "legendFormat": "{{ $Daemonset }}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes  * on(node) group_left() kube_node_labels{label_reservation!=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{ reservation!=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "Total Disk",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 34 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/sdc1$\",id=\"/\", reservation!=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "Restart Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{container != \"rest-protocol-stub1\",container != \"kafka-tools\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 36 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\", reservation!=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\", reservation!=\"monitoring\"}[2m]))"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 36 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/sdc1$\",id=\"/\", reservation!=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image !=\"\", reservation!=\"monitoring\"}[2m]))",
       "legendFormat": "Total CPU Usage"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\", reservation!=\"monitoring\"})",
       "legendFormat": "Total Memory Usage"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_fs_reads_total{image !=\"\",reservation!=\"monitoring\"}[2m]) + rate (container_fs_writes_total{id!=\"/\", reservation!=\"monitoring\"}[2m]) )",
       "legendFormat": "Total IOPS"
      }
     ]
    }
   ]
  }
 ]
}