{
 "title": "Hansen Provision - Msg Scheduler",
 "description": "Statistics from the msg scheduler",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Quartz",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate (com_sigma_samp_msgscheduler_quartz_scheduled_total[5m]))",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "sum(com_sigma_samp_msgscheduler_quartz_executing)",
     "legendFormat": "Executing"
    },
    {
     "expr": "sum(rate (com_sigma_samp_msgscheduler_quartz_completed_total[5m]))",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Timer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(com_sigma_samp_msgscheduler_timer_delay_seconds{quantile=\"0.9\"})",
     "legendFormat": "Delay"
    },
    {
     "expr": "avg(com_sigma_samp_msgscheduler_trigger_latency_seconds{quantile=\"0.99\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(com_sigma_samp_msgscheduler_store_entries > 0)",
     "legendFormat": "Store Size"
    },
    {
     "expr": "sum(com_sigma_samp_msgscheduler_quartz_misfired_total)",
     "legendFormat": "Misfired Total"
    }
   ]
  }
 ]
}