{
 "title": "Hansen Provision - Kubernetes Monitoring",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics (741)",
 "tags": [
  "kubernetes",
  "deployment"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Deployment", "query": "label_values(deployment)" },
   { "name": "Statefulset", "query": "label_values(statefulset)" },
   { "name": "Daemonset", "query": "label_values(daemonset)" },
   {
    "name": "Node",
    "query": "label_values(kube_node_labels{label_reservation=~\"$NodeType\"},node)"
   },
   {
    "name": "NodeType",
    "query": "label_values(kube_node_labels{label_reservation=~\".*\"},label_reservation)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Node Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", reservation=~\"^$NodeType$\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"^$Node.*$\"}  * on(node) group_left() kube_node_labels{label_reservation=~\"^$NodeType$\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Node CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\", kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"}[2m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/sdc1$\",id=\"/\",instance=~\"^$Node$\", reservation=~\"$NodeType\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/sdc1$\",id=\"/\",instance=~\"^$Node$\", reservation=~\"$NodeType\"}) * 100"
    },
    {}
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))) - ((sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)))) / ((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))) * 100"
    }
   ]
  },
  {
   "title": "Deployment memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"^$Node.*$\"}  * on(node) group_left() kube_node_labels{label_reservation=~\"$NodeType\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\", kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"}[2m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\",reservation=~\"$NodeType\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Node Mem Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"})"
    }
   ]
  },
  {
   "title": "Deployment Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"})"
    }
   ]
  },
  {
   "title": "Total Node CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"}[2m]))"
    }
   ]
  },
  {
   "title": "Deployment CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"}[2m]))"
    }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))",
     "legendFormat": "{{ $Daemonset }}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"^$Node.*$\"}  * on(node) group_left() kube_node_labels{label_reservation=~\"$NodeType\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image !=\"\", pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"}[2m])) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{ kubernetes_io_hostname }} | {{ pod_name }} "
    }
   ]
  },
  {
   "title": "CPU request",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{pod=~\"^$Deployment$Statefulset$Daemonset.*$\",node=~\"^$Node$\"}  * on(node) group_left() kube_node_labels{label_reservation=~\"$NodeType\"})  by (pod,node)",
     "legendFormat": "rqst: {{ node }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{kubernetes_io_hostname }} | {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory request",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{pod=~\"^$Deployment$Statefulset$Daemonset.*$\",node=~\"^$Node$\"}  * on(node) group_left() kube_node_labels{label_reservation=~\"$NodeType\"})  by (pod,node)",
     "legendFormat": "rqst: {{ node }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_fs_reads_total{image !=\"\", pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\", pod_name!=\"\", reservation=~\"$NodeType\"}[2m]) + rate (container_fs_writes_total{id!=\"/\",pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"}[2m]) ) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{kubernetes_io_hostname}} | {{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image !=\"\",pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"}[2m])) by (pod_name, kubernetes_io_hostname)",
     "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{image !=\"\",pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\", reservation=~\"$NodeType\"}[2m])) by (pod_name, kubernetes_io_hostname)",
     "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
    }
   ]
  }
 ]
}