{
 "title": "Hansen Provision - Minio Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": "prereq-minio-om,prereq-minio-wf"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disks offline",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(minio_disks_offline{kubernetes_pod_name=~\"^$Cluster.*$\"})"
    }
   ]
  },
  {
   "title": "Total Disks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(minio_disks_total{kubernetes_pod_name=~\"^$Cluster.*$\"})"
    }
   ]
  },
  {
   "title": "Disk Storage Space Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(disk_storage_used{kubernetes_pod_name=~\"^$Cluster.*$\"})/sum(disk_storage_total{kubernetes_pod_name=~\"^$Cluster.*$\"})*100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Inodes Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_inodes_used{persistentvolumeclaim=~\".*$Cluster.*$\"})/max(kubelet_volume_stats_inodes{persistentvolumeclaim=~\".*$Cluster.*$\"})*100"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(s3_requests_total{kubernetes_pod_name=~\"^$Cluster.*$\"}[2m])) by (kubernetes_pod_name,api)",
     "legendFormat": "{{api}}-{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(s3_requests_total{kubernetes_pod_name=~\"^$Cluster.*$\"}[2m])) by (api)",
     "legendFormat": "Total-{{api}}"
    }
   ]
  },
  {
   "title": "Minio Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(s3_rx_bytes_total{kubernetes_pod_name=~\"^$Cluster.*$\"}[2m])) by (kubernetes_pod_name)",
     "legendFormat": "Received-{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(s3_rx_bytes_total{kubernetes_pod_name=~\"^$Cluster.*$\"}[2m]))",
     "legendFormat": "Received-Total"
    },
    {
     "expr": "-sum(rate(s3_tx_bytes_total{kubernetes_pod_name=~\"^$Cluster.*$\"}[2m])) by (kubernetes_pod_name)",
     "legendFormat": "Transmitted-{{kubernetes_pod_name}}"
    },
    {
     "expr": "-sum(rate(s3_tx_bytes_total{kubernetes_pod_name=~\"^$Cluster.*$\"}[2m]))",
     "legendFormat": "Transmitted-Total"
    }
   ]
  },
  {
   "title": "Minio Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(s3_ttfb_seconds_sum{kubernetes_pod_name=~\"^$Cluster.*$\"}[2m])) by (api,kubernetes_pod_name)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(bucket_objects_count{kubernetes_pod_name=~\"^$Cluster.*$\"}) by (kubernetes_pod_name))",
     "legendFormat": "Object Count"
    }
   ]
  },
  { "title": "Resource Usage Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Storage space remaining",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(disk_storage_available{kubernetes_pod_name=~\"^$Cluster.*$\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(disk_storage_available{kubernetes_pod_name=~\"^$Cluster.*$\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{image !=\"\", pod_name=~\"^$Cluster.*$\"}[2m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", pod_name=~\"^$Cluster.*$\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Disk iops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_fs_reads_total{image !=\"\", pod_name=~\"^$Cluster.*$\"}[2m]) + rate (container_fs_writes_total{id!=\"/\",  pod_name=~\"^$Cluster.*$\"}[2m]) ) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image !=\"\",  pod_name=~\"^$Cluster.*$\"}[2m])) by (pod_name)",
     "legendFormat": "Received-{{pod_name}}"
    },
    {
     "expr": "-sum (rate (container_network_transmit_bytes_total{image !=\"\",  pod_name=~\"^$Cluster.*$\"}[2m])) by (pod_name)",
     "legendFormat": "Transmitted-{{pod_name}}"
    }
   ]
  },
  { "title": "Provisioning Export to Minio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Om Sub Inventory Minio Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(om_sub_inventory_io_seconds_sum[2m])/irate(om_sub_inventory_io_seconds_count[2m])) by (action) ",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Workflow Exporter Minio Uploads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(exporter_putRequest_seconds_count[2m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(exporter_putRequest_seconds_count[2m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Batch update time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(exporter_storeData_seconds_sum[2m])/rate(exporter_storeData_seconds_count[2m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Get request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(exporter_read_seconds_sum[2m])/rate(exporter_read_seconds_count[2m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}