{
 "title": "Hansen Provision - Workflow Engine",
 "tags": [
  "wf-core-engine",
  "hansen"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "1. Workflow Core Engine Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Input request rate (avg over 2m)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(wf_stream_input_requests_total[2m]) OR vector(0))"
    }
   ]
  },
  {
   "title": "Input requests to completed ratio",
   "type": "gauge",
   "description": "input requests /completed requests\nUsed to detect input request saturation.\nAlso includes requests completed with failures.\n",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(sum(irate(wf_stream_input_requests_total[2m])) by (process_name) / sum(irate(wf_stream_completed_requests_count_total[2m])))"
    }
   ]
  },
  {
   "title": "Avg request duration (ms)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(irate(wf_stream_completed_requests_millis_total[2m])) / avg(irate(wf_stream_completed_requests_count_total[2m]))"
    }
   ]
  },
  {
   "title": "Failed request  rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(wf_stream_completed_requests_count_total{status!=\"SUCCESS\"}[2m]) OR vector(0))"
    }
   ]
  },
  {
   "title": "Requests pressure",
   "type": "graph",
   "description": "Rate of incoming and  completed requests",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(wf_stream_input_requests_total[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(irate(wf_stream_completed_requests_count_total[2m]))",
     "legendFormat": "Completd"
    }
   ]
  },
  {
   "title": "Completed avg duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(avg(irate(wf_stream_completed_requests_millis_total[2m]))) / (avg(irate(wf_stream_completed_requests_count_total[2m])))",
     "legendFormat": "Overall avg duration"
    }
   ]
  },
  {
   "title": "2. Resource Usage Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\".*\"}[2m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\".*\"}[2m]))",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "Memory usage (stacked)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\", pod_name=~\"^.*$\",kubernetes_io_hostname=~\"^.*\"}) by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Memory usage (stacked)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\", pod_name=~\"wf-core-engine.*\",kubernetes_io_hostname=~\"^.*\"}) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Stacked CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image !=\"\", pod_name=~\"^.*\",kubernetes_io_hostname=~\"^.*$\"}[2m])) by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Cluster CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\".*\"}[2m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\".*\"}) * 100",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "AVG engine disk I/O pressure ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_writes_total{container_name=~\"wf-core-engine\"}[2m])) by(container_name)",
       "legendFormat": "writes {{ container_name }}"
      },
      {
       "expr": "-avg(irate(container_fs_reads_total{container_name=~\"wf-core-engine\"}[2m])) by(container_name)",
       "legendFormat": "writes {{ container_name }}"
      }
     ]
    },
    {
     "title": "Engine disk I/O pressure per pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(container_fs_writes_total{container_name=~\"wf-core-engine\"}[2m])) by(pod_name))  ",
       "legendFormat": "writes {{ pod_name }}"
      },
      {
       "expr": "-(sum(irate(container_fs_reads_total{container_name=~\"wf-core-engine\"}[2m])) by(pod_name))",
       "legendFormat": "reads {{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "3. Kafka Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total consumer lag per service",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumer_records_lag_avg_records >= 0 ) by(application)",
       "legendFormat": "{{ application }}"
      }
     ]
    },
    {
     "title": "consumer lag per topic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumer_records_lag_avg_records{application=\"wf-core-engine-wf\"} >= 0 ) by(topic)",
       "legendFormat": "{{ topic  }}"
      }
     ]
    },
    {
     "title": "I/O ratio",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(kafka_consumer_io_ratio{application=\"wf-core-engine-wf\",client_id=~\".*StreamThread-\\\\d+-consumer\"})",
       "legendFormat": "consumer"
      },
      {
       "expr": "avg(kafka_consumer_io_ratio{application=\"wf-core-engine-wf\",client_id=~\".*StreamThread-\\\\d+-restore-consumer\"})",
       "legendFormat": "restore consumer"
      },
      {
       "expr": "avg(kafka_consumer_io_ratio{application=\"wf-core-engine-wf\",client_id=~\".*-global-consumer\"})",
       "legendFormat": "global consumer"
      }
     ]
    },
    {
     "title": "Commit latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(kafka_consumer_commit_latency_avg_seconds{application=\"wf-core-engine-wf\",client_id=~\".*StreamThread-\\\\d+-consumer\"})",
       "legendFormat": "consumer"
      },
      {
       "expr": "avg(kafka_consumer_commit_latency_avg_seconds{application=\"wf-core-engine-wf\",client_id=~\".*StreamThread-\\\\d+-restore-consumer\"})",
       "legendFormat": "restore consumer"
      },
      {
       "expr": "avg(kafka_consumer_commit_latency_avg_seconds{application=\"wf-core-engine-wf\",client_id=~\".*-global-consumer\"})",
       "legendFormat": "global consumer"
      }
     ]
    },
    {
     "title": "Commit rates",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "avg(kafka_consumer_commit_rate_commits{application=\"wf-core-engine-wf\",client_id=~\".*StreamThread-\\\\d+-consumer\"})",
       "legendFormat": "consumer"
      },
      {
       "expr": "avg(kafka_consumer_commit_rate_commits{application=\"wf-core-engine-wf\",client_id=~\".*StreamThread-\\\\d+-restore-consumer\"})",
       "legendFormat": "restore consumer"
      },
      {
       "expr": "avg(kafka_consumer_commit_rate_commits{application=\"wf-core-engine-wf\",client_id=~\".*-global-consumer\"})",
       "legendFormat": "global consumer"
      }
     ]
    },
    {
     "title": "Avg sync time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(kafka_consumer_sync_time_avg_seconds{application=\"wf-core-engine-wf\",client_id=~\".*StreamThread-\\\\d+-consumer\"})",
       "legendFormat": "consumer"
      },
      {
       "expr": "avg(kafka_consumer_sync_time_avg_seconds{application=\"wf-core-engine-wf\",client_id=~\".*StreamThread-\\\\d+-restore-consumer\"})",
       "legendFormat": "restore consumer"
      },
      {
       "expr": "avg(kafka_consumer_sync_time_avg_seconds{application=\"wf-core-engine-wf\",client_id=~\".*-global-consumer\"})",
       "legendFormat": "global consumer"
      }
     ]
    }
   ]
  },
  {
   "title": "4. Per instance details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Req rate per wf instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(wf_stream_input_requests_total[2m]))by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Completed requests per wf instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(wf_stream_completed_requests_count_total[2m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Completed  request avg duration per instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(avg(irate(wf_stream_completed_requests_millis_total[2m])) by (instance)) / (avg(irate(wf_stream_completed_requests_count_total[2m])) by (instance))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Assigned partitions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumer_assigned_partitions{application=\"wf-core-engine-wf\",client_id=~\".*StreamThread-[0-9]+-consumer\"}) by (kubernetes_pod_name)",
       "legendFormat": "{{ kubernetes_pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "5. Workflow Process details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Submitted/completed ratio",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "avg(sum(irate(wf_stream_exec_process_count_total[2m])) by (process_name) / sum(irate(wf_stream_exec_process_completed_count_total[2m])) by (process_name))"
      }
     ]
    },
    {
     "title": "Longest 5 process",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 5, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk( 5 , avg(((irate(wf_stream_exec_process_completed_millis_total[2m]) / irate(wf_stream_exec_process_completed_count_total[2m]) ) >= 0)) by (process_name))",
       "legendFormat": "{{ process_name }}"
      }
     ]
    },
    {
     "title": "Process duration",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 20 },
     "targets": [
      {
       "expr": "avg(((irate(wf_stream_exec_process_completed_millis_total[2m]) / irate(wf_stream_exec_process_completed_count_total[2m]) ) >= 0)) by (process_name)",
       "legendFormat": "{{ process_name }}"
      }
     ]
    }
   ]
  }
 ]
}