{
 "title": "Hansen Provision - Elasticsearch Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read Only Indices",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_indices_settings_stats_read_only_indices\t"
    }
   ]
  },
  {
   "title": "Cluster Health",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_status) by (color)",
     "legendFormat": "{{color}}"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((sum(elasticsearch_filesystem_data_size_bytes) by (name)-sum(elasticsearch_filesystem_data_available_bytes)by (name))/sum(elasticsearch_filesystem_data_size_bytes)by (name)*100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Resource Usage Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Disk Space Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_filesystem_data_available_bytes) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image !=\"\", pod_name=~\"^elasticsearch-master-.*$\"}[2m])) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", pod_name=~\"^elasticsearch-master-.*$\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Disk iops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_fs_reads_total{image !=\"\",pod_name=~\"^elasticsearch-master-.*$\"}[2m]) + rate (container_fs_writes_total{id!=\"/\",pod_name=~\"elasticsearch-master-.*$\"}[2m]) ) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image !=\"\",pod_name=~\"^elasticsearch-master-.*$\"}[2m])) by (pod_name)",
     "legendFormat": "Received-{{pod_name}}"
    },
    {
     "expr": "-sum (rate (container_network_transmit_bytes_total{image !=\"\",pod_name=~\"^elasticsearch-master-.*$\"}[2m])) by (pod_name)",
     "legendFormat": "Transmitted-{{pod_name}}"
    }
   ]
  },
  {
   "title": "Elasticsearch Application Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indexing Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_indices_indexing_index_total\t[2m])) by (name)\t",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Active Shards",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_active_primary_shards",
       "legendFormat": "Primary Shards"
      },
      {
       "expr": "elasticsearch_cluster_health_active_shards",
       "legendFormat": "All Shards"
      }
     ]
    }
   ]
  }
 ]
}