{
 "title": "Confluent Platform",
 "tags": [ "5.1.2" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   {
    "name": "component_name",
    "label": "Component",
    "query": "label_values(physicalstatefulcluster_core_confluent_cloud_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Confluent Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Brokers Online",
     "type": "singlestat",
     "description": "Number of Brokers Online",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kafka_server_replicamanager_value{name=\"LeaderCount\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"})"
      }
     ]
    },
    {
     "title": "Active Controllers",
     "type": "singlestat",
     "description": "Number of active controllers in the cluster.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum(kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"}))"
      }
     ]
    },
    {
     "title": "Unclean Leader Election Rate",
     "type": "singlestat",
     "description": "Unclean leader election rate",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_controller_controllerstats_oneminuterate{name=~\"UncleanLeaderElectionsPerSec\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"})"
      }
     ]
    },
    {
     "title": "Online Partitions",
     "type": "singlestat",
     "description": "Partitions that are online",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_value{name=~\"PartitionCount\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"})"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "singlestat",
     "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_value{name=~\"UnderReplicatedPartitions\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"})"
      }
     ]
    },
    {
     "title": "Offline Partitions Count",
     "type": "singlestat",
     "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_value{name=~\"OfflineReplicaCount\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Aggregated Kafka Broker Pods CPU Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{pod_name=~\"$component_name-(\\\\d+)\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod_name=~\"$component_name-(\\\\d+)\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage (Data)",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"data0-$component_name.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Disk Usage (Log)",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"log-$component_name.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Messages In Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"MessagesInPerSec\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"})",
       "legendFormat": "{{Messages In Per Second}}"
      }
     ]
    },
    {
     "title": "Byte Rate",
     "type": "graph",
     "description": "Byte Rate",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"})",
       "legendFormat": "Incoming Byte Rate"
      },
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"})",
       "legendFormat": "Outgoing Byte Rate"
      }
     ]
    },
    {
     "title": "Fetch Request Rate",
     "type": "graph",
     "description": "Fetch Request Rate",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=~\"TotalFetchRequestsPerSec\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"})",
       "legendFormat": "Fetch Request Rate"
      },
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=~\"FailedFetchRequestsPerSec\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"})",
       "legendFormat": "Failed Fetch Request Rate"
      }
     ]
    },
    {
     "title": "Produce Request Rate",
     "type": "graph",
     "description": "Produce Request Rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"TotalProduceRequestsPerSec\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"})",
       "legendFormat": "Total Produce Request Rate"
      },
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"FailedProduceRequestsPerSec\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"})",
       "legendFormat": "Failed Produce Request Rate"
      }
     ]
    },
    {
     "title": "Request Handler Avg Idle Percent",
     "type": "graph",
     "description": "Request Handler Avg Idle Percent",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_kafkarequesthandlerpool_oneminuterate{name=~\"RequestHandlerAvgIdlePercent\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"}*100",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Network Processor Avg Idle Percent",
     "type": "graph",
     "description": "Network Processor Avg Idle Percent",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_network_socketserver_value{name=~\"NetworkProcessorAvgIdlePercent\",kubernetes_namespace=~\"$namespace\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\"}*100",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Kafka Connect/Replicator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Connectors",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_count{physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})",
       "legendFormat": "{{ kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Connector Startup Success Total",
     "type": "singlestat",
     "description": "The total number of connector starts that succeeded.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_startup_success_total{physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Connector Startup Failure Total",
     "type": "singlestat",
     "description": "The total number of connector starts that failed.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_startup_failure_total{physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Number of Tasks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_task_count{physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Task Startup Success Total",
     "type": "singlestat",
     "description": "The total number of task starts that succeeded.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_task_startup_success_total{physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Task Startup Failure Total",
     "type": "singlestat",
     "description": "The total number of task starts that failed.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_task_startup_failure_total{physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Connect Metrics: IO Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_io_ratio{physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{ kubernetes_pod_name }}"
      }
     ]
    },
    {
     "title": "Connect Metrics: Incoming Byte Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_incoming_byte_rate{physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Connect Metrics: Network IO Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_network_io_rate{physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent KSQL Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "KSQL Metrics: Bytes Consumed",
     "type": "graph",
     "description": "Total number of bytes consumed.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"io_confluent_ksql_metrics_ksql_engine_query_stats_confluent_ksql_.*_ksqlbytes_consumed_total\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{ kubernetes_pod_name }}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Messages Consumed",
     "type": "graph",
     "description": "Messages consumed per second.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"io_confluent_ksql_metrics_ksql_engine_query_stats_confluent_ksql_.*_ksqlmessages_consumed_per_sec\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{ kubernetes_pod_name }}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Messages Produced",
     "type": "graph",
     "description": "Messages produced per second.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"io_confluent_ksql_metrics_ksql_engine_query_stats_confluent_ksql_.*_ksqlmessages_produced_per_sec\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{ kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Active Queries",
     "type": "graph",
     "description": "Number of active queries.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"io_confluent_ksql_metrics_ksql_engine_query_stats_confluent_ksql_.*_ksqlnum_active_queries\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{ kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Idle Queries",
     "type": "graph",
     "description": "Number of idle queries.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"io_confluent_ksql_metrics_ksql_engine_query_stats_confluent_ksql_.*_ksqlnum_idle_queries\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Persistent Queries",
     "type": "graph",
     "description": "Number of persistent queries.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"io_confluent_ksql_metrics_ksql_engine_query_stats_confluent_ksql_.*_ksqlnum_persistent_queries\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": " {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Schema Registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Kafka Schema Registry servers",
     "type": "singlestat",
     "description": "Number of Kafka Schema Registry servers",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count({__name__=~\"schemaregistry_.*_jetty_metrics_connections_active\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "singlestat",
     "description": "Total number of active TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum({__name__=~\"schemaregistry_.*_jetty_metrics_connections_active\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Open Rate",
     "type": "singlestat",
     "description": "The average rate per second of opened TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg({__name__=~\"schemaregistry_.*_jetty_metrics_connections_opened_rate\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Close Rate",
     "type": "singlestat",
     "description": "The average rate per second of closed TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg({__name__=~\"schemaregistry_.*_jetty_metrics_connections_closed_rate\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quorum Size",
     "type": "singlestat",
     "description": "Quorum Size of Zookeeper ensemble",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg({__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_quorumsize\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Alive Connections",
     "type": "singlestat",
     "description": "Number of Alive Connections",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum({__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_numaliveconnections\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Outstanding Requests",
     "type": "graph",
     "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_outstandingrequests\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"}  ",
       "legendFormat": "{{kubernetes_pod_name}}-{{name2}}"
      }
     ]
    },
    {
     "title": "Number of ZNodes",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg({__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_nodecount\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Number of Watchers",
     "type": "singlestat",
     "description": "Number of Watchers",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum({__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_watchcount\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Request Latency - Minimum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_minrequestlatency\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage (txnlog)",
     "type": "graph",
     "description": "Zookeeper Disk Usage (txnlog)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"txnlog-$component_name.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Disk Usage (Data)",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"data-$component_name.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Request Latency - Maximum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_maxrequestlatency\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Latency - Average",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"org_apache_zookeeperservice_replicatedserver_.*_avgrequestlatency\",physicalstatefulcluster_core_confluent_cloud_name=~\"$component_name\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}