{
 "title": "Hansen Provision - Fluentbit Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   { "name": "app_name", "query": "fluentbit" }
  ]
 },
 "panels": [
  {
   "title": "Deployment memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\", pod_name=~\"^.*$app_name.*$\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (kube_node_status_allocatable_memory_bytes{node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\", pod_name=~\".*$app_name.*$\",kubernetes_io_hostname=~\"^$Node$\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((((sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\"^.*$app_name.*$\"}) or vector(0))) - (sum(kube_daemonset_status_number_ready{daemonset=~\"^.*$app_name.*$\"}) or vector(0)))/ (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\"^.*$app_name.*$\"}) or vector(0))) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\", pod_name=~\".*$app_name.*$\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\", pod_name=~\"^.*$app_name.*$\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable_memory_bytes{node=~\"^$Node.*$\"})"
    }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_number_ready{daemonset=~\"^.*$app_name.*$\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\"^.*$app_name.*$\"}) or vector(0)",
     "legendFormat": "{{ $Daemonset }}"
    }
   ]
  },
  {
   "title": "fluentbit log records input ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total[2m]))"
    }
   ]
  },
  {
   "title": "log records produced",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(logback_events_total[2m]))"
    }
   ]
  },
  {
   "title": "fluentbit throughput state",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(logback_events_total[2m]))/sum(rate(fluentbit_input_records_total[2m]))) "
    }
   ]
  },
  {
   "title": "Log Flow Rate by pod",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total[2m]))by(kubernetes_pod_name)",
     "legendFormat": "input {{kubernetes_pod_name}}"
    },
    {
     "expr": "- sum(rate(fluentbit_output_proc_records_total[2m]))by(kubernetes_pod_name)",
     "legendFormat": "output {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Log Flow Rate Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total[2m]))",
     "legendFormat": "Total input"
    },
    {
     "expr": "- sum(rate(fluentbit_output_proc_records_total[2m]))",
     "legendFormat": "Total output"
    }
   ]
  },
  {
   "title": "Log Size Flow Rate by pod",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total[2m]))by(kubernetes_pod_name)",
     "legendFormat": "input {{kubernetes_pod_name}}"
    },
    {
     "expr": "- sum(rate(fluentbit_output_proc_bytes_total[2m]))by(kubernetes_pod_name)",
     "legendFormat": "output {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Log Size Flow Rate Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total[2m]))",
     "legendFormat": "Total input"
    },
    {
     "expr": "- sum(rate(fluentbit_output_proc_bytes_total[2m]))",
     "legendFormat": "Total output"
    }
   ]
  },
  {
   "title": "Log Events Produced",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logback_events_total[2m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(logback_events_total[2m])) + sum(rate(logback_appender_total[2m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(logback_appender_total[2m]))  by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Fluentbit errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total[2m]))by(kubernetes_pod_name)",
     "legendFormat": "fluentbit_output_retries_failed_total {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_total[2m]))by(kubernetes_pod_name)",
     "legendFormat": "fluentbit_output_retries_total {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(fluentbit_output_errors_total[2m]))by(kubernetes_pod_name)",
     "legendFormat": "fluentbit_output_errors_total {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod_name=~\".*$app_name.*$\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{ kubernetes_io_hostname }} | {{ pod_name }} "
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{pod=~\"^.*$app_name.*$\",node=~\"^$Node$\"}) by (pod,node)",
     "legendFormat": "rqst: {{ node }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\", pod_name=~\"^.*$app_name.*$\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{kubernetes_io_hostname }} | {{ pod_name }}"
    },
    {
     "expr": "sum ((kube_pod_container_resource_requests_memory_bytes{pod=~\"^.*$app_name.*$\",node=~\"^$Node$\"})) by (pod,node)",
     "legendFormat": "rqst: {{ node }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod_name=~\"^.*$app_name.*$\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (pod_name, kubernetes_io_hostname)",
     "legendFormat": "received {{ kubernetes_io_hostname }} | {{ pod_name }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod_name=~\"^.*$app_name.*$\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (pod_name, kubernetes_io_hostname)",
     "legendFormat": "transmitted {{ kubernetes_io_hostname }} | {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_fs_reads_total{pod_name=~\"^.*$app_name.*$\",kubernetes_io_hostname=~\"^$Node$\"}[2m]) + rate (container_fs_writes_total{pod_name=~\"^.*$app_name.*$\",kubernetes_io_hostname=~\"^$Node$\"}[2m]) ) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{kubernetes_io_hostname}} | {{pod_name}}"
    }
   ]
  }
 ]
}