{
 "title": "Hansen Provision - Order Manager",
 "tags": [
  "hansen",
  "om-engine"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "1. Order Manager Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Order Input",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(om_order_start_counter_total[2m]))"
    }
   ]
  },
  {
   "title": "Order Input Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(om_order_start_counter_total[2m]))",
     "legendFormat": "{{order input}}"
    }
   ]
  },
  {
   "title": "Order Duration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(irate(om_order_from_create_seconds_sum{state=\"closed.completed.all\"}[2m])*1000/irate(om_order_from_create_seconds_count{state=\"closed.completed.all\"}[2m]))"
    }
   ]
  },
  {
   "title": "Order Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(om_order_from_create_seconds_sum[2m])/irate(om_order_from_create_seconds_count[2m])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "2. Order Manager Performance  Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Duration",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(om_task_instance_done_duration_seconds_sum[2m]) /irate(om_task_instance_done_duration_seconds_count[2m])) by (task_id)",
       "legendFormat": "{{task_id}}"
      }
     ]
    },
    {
     "title": "Time to create WF Req",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(om_create_wf_request_seconds_sum[2m])/irate(om_create_wf_request_seconds_count[2m])) by (plan_name)",
       "legendFormat": "{{plan_name}}"
      }
     ]
    },
    {
     "title": "Engine Processor Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(om_engine_processor_seconds_sum[2m])/irate(om_engine_processor_seconds_count[2m]))"
      }
     ]
    },
    {
     "title": "Object Store Access Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(om_object_store_access_duration_seconds_sum[2m])/irate(om_object_store_access_duration_seconds_count[2m])) by (topic, action)",
       "legendFormat": "{{topic}}={{action}}"
      }
     ]
    },
    {
     "title": "Order Index Update Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(om_index_update_seconds_sum[2m])/irate(om_index_update_seconds_count[2m]))"
      }
     ]
    },
    {
     "title": "STM Rest Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(om_topology_rest_call_seconds_sum[2m])/irate(om_topology_rest_call_seconds_count[2m]))"
      }
     ]
    },
    {
     "title": "WF Message Latency from order created",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(om_message_interval_seconds_sum[2m])/irate(om_message_interval_seconds_count[2m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Subscriber Inventory Read/Write Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(om_sub_inventory_io_seconds_sum[2m])/irate(om_sub_inventory_io_seconds_count[2m])) by (action)",
       "legendFormat": "{{action}}"
      }
     ]
    }
   ]
  },
  {
   "title": "3. Kafka Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Record Consumed Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_consumed_rate{application=~\"om.*\"}) by (application)",
       "legendFormat": "{{application}}"
      }
     ]
    },
    {
     "title": "Producer Message Wait (ms)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(kafka_producer_record_queue_time_avg{application=~\"om.*\"}>0) by (application)",
       "legendFormat": "{{application}}"
      }
     ]
    },
    {
     "title": "Kafka Consumer Lag by Topic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_lag_max{application=~\"om.*\"}>=0) by (application)",
       "legendFormat": "{{application}}"
      }
     ]
    }
   ]
  },
  {
   "title": "4. Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS per container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(container_fs_writes_total{container_name=~\"om-.*\"}[2m])) by(container_name))  "
      }
     ]
    }
   ]
  },
  {
   "title": "5. Order Manager Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Center Pending Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(om_error_center_pending_error_count)"
      }
     ]
    },
    {
     "title": "Context Cache Evictions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(om_engine_context_cache_evictions_total[2m])"
      }
     ]
    },
    {
     "title": "Uniqueness Store Entry Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "om_uniqueness_manager_store_size"
      }
     ]
    },
    {
     "title": "Engine Lock Store Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "om_engine_entity_lock_store_size"
      }
     ]
    },
    {
     "title": "Average Rest API Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(http_server_requests_seconds_sum{application=~\"om-.*\",uri!~\"/actuator.*\"}[2m])/irate(http_server_requests_seconds_count{application=~\"om-.*\",uri!~\"/actuator.*\"}[2m])) by (application,uri)",
       "legendFormat": "{{uri}}@{{application}}"
      }
     ]
    },
    {
     "title": "Max Rest API Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{application=~\"om-.*\", uri!~\"/actuator.*\"}",
       "legendFormat": "{{uri}}@{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "6. Pending Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Object Store Pending Update Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "om_object_store_store_size" }
     ]
    },
    {
     "title": "Order Index Pending Update Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "om_order_search_store_size" }
     ]
    },
    {
     "title": "Engine Pending Order Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "om_engine_pending_order_store_size"
      }
     ]
    },
    {
     "title": "Order Inventory Pending Order Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "om_order_inventory_store_size" }
     ]
    }
   ]
  },
  {
   "title": "7. Order Manager Recovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "OM Recovery Pending Order Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "om_order_recovery_pending_order_count"
      }
     ]
    },
    {
     "title": "OM Recovery Replication Lag (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(om_order_recovery_message_lag_seconds_sum[2m])/irate(om_order_recovery_message_lag_seconds_count[2m])) by (topic)"
      }
     ]
    }
   ]
  }
 ]
}