apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-exporter
  namespace: monitoring
  labels:
    k8s-app: mongo-exporter
spec:
  selector:
    matchLabels:
      k8s-app: mongo-exporter
  template:
    metadata:
      labels:
        k8s-app: mongo-exporter
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9104"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: mongo-exporter
        image: infra-harbor-paas.attmx-ne.local/matrixx_lab01/noenv/mongo-exporter:latest
        args: ["--web.listen-address=:9104", "--mongodb.uri", "mongodb://mongos-0.mongodb.svc.cluster.local:27017,mongos-1.mongodb.svc.cluster.local:27017,mongos-2.mongodb.svc.cluster.local:27017,mongos-3.mongodb.svc.cluster.local:27017"]
        ports:
        - containerPort: 9104
          name: http
      imagePullSecrets:
        - name: regcred
