apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-mongodb-exporter
  name: test-mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-mongodb-exporter
  template:
    metadata:
      labels:
        app: test-mongodb-exporter
    spec:
      containers:
      - image: bitnami/mongodb-exporter
        name: mongodb-exporter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-mongodb-exporter
  name: test-mongodb-exporter
spec:
  ports:
  - port: 9216
    protocol: TCP
    targetPort: 9216
  selector:
    app: test-mongodb-exporter
  sessionAffinity: None
  type: ClusterIP