{
 "title": "1   Matrixx Summary",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "subdomain", "label": "Subdomain", "query": "label_values(subdomain)" }
  ]
 },
 "panels": [
  {
   "title": "Subdomain-1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(avg(kube_pod_status_phase{job=\"kube-state-metrics\", namespace=~\"mtx-attm-sit\",phase=~\"Running\", pod=~\"ckpt.*|proc.*|publ.*|tra.*|gatewayproxy.*|activemq.*\"}) != 1)",
     "legendFormat": "Pods/Blades (T)"
    },
    {
     "expr": "count(100 * (1 - ((avg_over_time(statSysInfoPhysicalMemoryFreeMb{subdomain=\"subdomain-1\"}[24h]) + avg_over_time(statSysInfoPhysicalMemoryCachedMb{subdomain=\"subdomain-1\"}[24h]) + avg_over_time(statSysInfoPhysicalMemoryBuffersMb{subdomain=\"subdomain-1\"}[24h])) / avg_over_time(statSysInfoPhysicalMemoryTotalMb{subdomain=\"subdomain-1\"}[24h]))) > 60)",
     "legendFormat": "Memory (T)"
    },
    {
     "expr": "count(sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"shared\", subdomain=~\"subdomain-1\"}) + sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"local\", subdomain=~\"subdomain-1\"}) > 60) - 0",
     "legendFormat": "Disk (T)"
    },
    {
     "expr": "sum(diamTotalStatsProtocolErrors{subdomain=\"subdomain-1\"}) > 100"
    },
    {
     "expr": "count(rate(sysProcessingErrors{subdomain=\"subdomain-1\"}[5m]) > 100)",
     "legendFormat": "Processing Errors"
    }
   ]
  },
  {
   "title": "Subdomain-2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(avg(kube_pod_status_phase{job=\"kube-state-metrics\", namespace=~\"mtx-attm-sit\",phase=~\"Running\", pod=~\"ckpt.*|proc.*|publ.*|tra.*|gatewayproxy.*|activemq.*\"}) != 1)",
     "legendFormat": "Pods/Blades (T)"
    },
    {
     "expr": "count(100 * (1 - ((avg_over_time(statSysInfoPhysicalMemoryFreeMb{subdomain=\"subdomain-2\"}[24h]) + avg_over_time(statSysInfoPhysicalMemoryCachedMb{subdomain=\"subdomain-2\"}[24h]) + avg_over_time(statSysInfoPhysicalMemoryBuffersMb{subdomain=\"subdomain-2\"}[24h])) / avg_over_time(statSysInfoPhysicalMemoryTotalMb{subdomain=\"subdomain-2\"}[24h]))) > 60)",
     "legendFormat": "Memory (T)"
    },
    {
     "expr": "count(sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"shared\", subdomain=~\"subdomain-2\"}) + sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"local\", subdomain=~\"subdomain-2\"}) > 60) - 0",
     "legendFormat": "Disk (T)"
    },
    {
     "expr": "sum(diamTotalStatsProtocolErrors{subdomain=\"subdomain-2\"}) > 100"
    },
    {
     "expr": "count(rate(sysProcessingErrors{subdomain=\"subdomain-2\"}[5m]) > 100)",
     "legendFormat": "Processing Errors"
    }
   ]
  },
  {
   "title": "Subdomain-3",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(avg(kube_pod_status_phase{job=\"kube-state-metrics\", namespace=~\"mtx-attm-sit\",phase=~\"Running\", pod=~\"ckpt.*|proc.*|publ.*|tra.*|gatewayproxy.*|activemq.*\"}) != 1)",
     "legendFormat": "Pods/Blades (T)"
    },
    {
     "expr": "count(avg(sysPeerClusterClusterState{instance=~\"proc-s1.*\", sysPeerClusterClusterId=\"1\",sysPeerClusterEngineId=~\"1|2\", subdomain=~\"subdomain-3\"}) != 7)",
     "legendFormat": "Engine (T)"
    },
    {
     "expr": "count(100 * (1 - ((avg_over_time(statSysInfoPhysicalMemoryFreeMb{subdomain=\"subdomain-3\"}[24h]) + avg_over_time(statSysInfoPhysicalMemoryCachedMb{subdomain=\"subdomain-3\"}[24h]) + avg_over_time(statSysInfoPhysicalMemoryBuffersMb{subdomain=\"subdomain-3\"}[24h])) / avg_over_time(statSysInfoPhysicalMemoryTotalMb{subdomain=\"subdomain-3\"}[24h]))) > 60)",
     "legendFormat": "Memory (T)"
    },
    {
     "expr": "count(sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"shared\", subdomain=~\"subdomain-3\"}) + sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"local\", subdomain=~\"subdomain-3\"}) > 60) - 0",
     "legendFormat": "Disk (T)"
    },
    {
     "expr": "sum(diamTotalStatsProtocolErrors{subdomain=\"subdomain-3\"}) > 100"
    },
    {
     "expr": "count(rate(sysProcessingErrors{subdomain=\"subdomain-3\"}[5m]) > 100)",
     "legendFormat": "Processing Errors"
    }
   ]
  },
  { "title": "VISIBLE MATRIXX Eye On Glass", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Engine1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(sysPeerClusterClusterState{instance=~\"proc-s1.*\", sysPeerClusterClusterId=\"1\",sysPeerClusterEngineId=\"1\", subdomain=~\"$subdomain\"})"
    }
   ]
  },
  {
   "title": "Engine2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(sysPeerClusterClusterState{instance=~\"proc-s1.*\", sysPeerClusterClusterId=\"1\",sysPeerClusterEngineId=\"2\", subdomain=~\"$subdomain\"})"
    }
   ]
  },
  {
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sysClusterMemberMgmtIpAddress{instance=~\"proc-s1e1.*\", subdomain=~\"$subdomain\"} - 0 "
    },
    {
     "expr": "sysPeerClusterClusterState{ instance=~\"proc-s1e1.*\", sysPeerClusterClusterId=\"1\", sysPeerClusterEngineId=\"1\", subdomain=~\"$subdomain\"} - 0 "
    },
    {
     "expr": "sysClusterMemberNodeState{instance=~\"proc-s1e1.*\", subdomain=~\"$subdomain\"} - 0"
    },
    {
     "expr": "sysClusterMemberNodeId{instance=~\"proc-s1e1.\", subdomain=~\"$subdomain\"} - 0"
    }
   ]
  },
  {
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sysClusterMemberMgmtIpAddress{instance=~\"publ-s1e1.*\", subdomain=~\"$subdomain\"} - 0 "
    },
    {
     "expr": "sysPeerClusterClusterState{ instance=~\"publ-s1e1.*\", sysPeerClusterClusterId=\"2\", sysPeerClusterEngineId=\"1\", subdomain=~\"$subdomain\"} - 0 "
    },
    {
     "expr": "sysClusterMemberNodeState{instance=~\"publ-s1e1.*\", subdomain=~\"$subdomain\"} - 0"
    },
    {
     "expr": "sysClusterMemberNodeId{instance=~\"publ-s1e1.\", subdomain=~\"$subdomain\"} - 0"
    }
   ]
  },
  {
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sysClusterMemberMgmtIpAddress{instance=~\"proc-s1e2.*\", subdomain=~\"$subdomain\"} - 0 "
    },
    {
     "expr": "sysPeerClusterClusterState{ instance=~\"proc-s1e2.*\", sysPeerClusterClusterId=\"1\", sysPeerClusterEngineId=\"2\", subdomain=~\"$subdomain\"} - 0 "
    },
    {
     "expr": "sysClusterMemberNodeState{instance=~\"proc-s1e2.*\", subdomain=~\"$subdomain\"} - 0"
    },
    {
     "expr": "sysClusterMemberNodeId{instance=~\"proc-s1e2.*\", subdomain=~\"$subdomain\"} - 0"
    }
   ]
  },
  {
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "sysClusterMemberMgmtIpAddress{instance=~\"publ-s1e2.*\", subdomain=~\"$subdomain\"} - 0 "
    },
    {
     "expr": "sysPeerClusterClusterState{ instance=~\"publ-s1e2.*\", sysPeerClusterClusterId=\"2\", sysPeerClusterEngineId=\"2\", subdomain=~\"$subdomain\"} - 0 "
    },
    {
     "expr": "sysClusterMemberNodeState{instance=~\"publ-s1e2.*\", subdomain=~\"$subdomain\"} - 0"
    },
    {
     "expr": "sysClusterMemberNodeId{instance=~\"publ-s1e2.*\", subdomain=~\"$subdomain\"} - 0"
    }
   ]
  },
  {
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "tfcCfgVipAddress{instance=~\"tralb.*\", subdomain=~\"$subdomain\"} - 0"
    },
    {
     "expr": "sysTraPeerNodeState{instance=~\"tralb.*\", subdomain=~\"$subdomain\"} - 0 "
    },
    {
     "expr": "sysTraNodeState{instance=~\"tralb.*\", subdomain=~\"$subdomain\"} - 0"
    }
   ]
  },
  {
   "title": "TRA- Disaster Recovery",
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "tfcCfgVipAddress{instance=~\"tra-dr-.*|trart.*\"} - 0"
    },
    {
     "expr": "sysTraPeerNodeState{instance=~\"tra-dr-.*|trart.*\"} - 0 "
    },
    {
     "expr": "sysTraNodeState{instance=~\"tra-dr-.*|trart.*\"} - 0"
    }
   ]
  },
  {
   "title": "Checkpoint",
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "sysClusterMemberMgmtIpAddress{instance=~\"ckpt-.*\", subdomain=~\"$subdomain\"} - 0 "
    },
    {
     "expr": "sysPeerClusterClusterState{instance=~\"ckpt-.*\", sysPeerClusterClusterId=\"3\", subdomain=~\"$subdomain\"} - 0 "
    },
    {
     "expr": "sysClusterMemberNodeState{instance=~\"ckpt-.*\", subdomain=~\"$subdomain\"} - 0"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(statSysInfoPhysicalMemoryFreeMb{subdomain=~\"$subdomain\"}[24h]) + avg_over_time(statSysInfoPhysicalMemoryCachedMb[24h]) + avg_over_time(statSysInfoPhysicalMemoryBuffersMb{subdomain=~\"$subdomain\"}[24h])) / avg_over_time(statSysInfoPhysicalMemoryTotalMb{subdomain=~\"$subdomain\"}[24h])))"
    }
   ]
  },
  {
   "title": "All Matrixx Disk Utilization",
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"shared\", subdomain=~\"$subdomain\"}) - 0"
    },
    {
     "expr": "sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"local\", subdomain=~\"$subdomain\"}) - 0"
    },
    {
     "expr": "sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"shared\", subdomain=~\"$subdomain\"}) + sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"local\", subdomain=~\"$subdomain\"})"
    }
   ]
  },
  {
   "title": "Publishing Blades System Memory Pool Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sysTotalMemoryPoolInUseMb{subdomain=~\"$subdomain\", instance=~\"publ.*\"}) * 100 / (sysTotalMemoryPoolSizeMb{subdomain=~\"$subdomain\", instance=~\"publ.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IMDB Synch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Memory Stats",
     "type": "table-old",
     "description": " ",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "txnDatabaseName{subdomain=~\"$subdomain\",instance=~\"proc-s1e1.*\"} - 0"
      },
      {
       "expr": "txnDatabaseMemoryFreeKb{subdomain=~\"$subdomain\",instance=~\"proc-s1e1.*\"} - 0"
      },
      {
       "expr": "txnDatabaseMemoryUsedKb{subdomain=~\"$subdomain\",instance=~\"proc-s1e1.*\"} - 0"
      },
      {
       "expr": "txnDatabaseMemoryReclaimableCount{subdomain=~\"$subdomain\",instance=~\"proc-s1e1.*\"} - 0"
      },
      {
       "expr": "txnDatabaseMemoryReclaimableKb{subdomain=~\"$subdomain\",instance=~\"proc-s1e1.*\"} - 0"
      },
      {
       "expr": "txnDatabaseMemoryGrowthLastMinuteInKb{subdomain=~\"$subdomain\",instance=~\"proc-s1e1.*\"} - 0"
      },
      {
       "expr": "txnDatabaseMemoryGrowthLastHourInKb{subdomain=~\"$subdomain\",instance=~\"proc-s1e1.*\"} - 0"
      },
      {
       "expr": "txnDatabaseMemoryGrowthLastDayInKb{subdomain=~\"$subdomain\",instance=~\"proc-s1e1.*\"} - 0"
      }
     ]
    },
    {
     "title": "Database Synch",
     "type": "table-old",
     "description": " ",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "txnDatabaseObjectName{instance=~\"proc-s1e1-0.*\",txnDatabaseObjectPoolId=\"5\", subdomain=~\"$subdomain\"} - 0"
      },
      {
       "expr": "sum without (instance) (txnDatabaseObjectCount{instance=~\"proc-s1e1-0.*\", txnDatabaseObjectPoolId=\"5\", subdomain=~\"$subdomain\"}) - 0"
      },
      {
       "expr": "sum without (instance) (txnDatabaseObjectCount{instance=~\"publ-s1e1-0.*\", txnDatabaseObjectPoolId=\"5\", subdomain=~\"$subdomain\"}) - 0"
      },
      {
       "expr": "sum without (instance) (txnDatabaseObjectCount{instance=~\"ckpt-s1e1-0.*\", txnDatabaseObjectPoolId=\"5\", subdomain=~\"$subdomain\"}) - 0"
      }
     ]
    }
   ]
  },
  {
   "title": "MATRIXX Diameter Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diamResultCodeStatsResultCodeOut{subdomain=~\"$subdomain\"}[5m])",
       "legendFormat": "{{diamResultCodeStatsApplicationId}} - {{diamResultCodeStatsCmdCode}} - {{diamResultCodeStatsResultCode}}"
      }
     ]
    },
    {
     "title": "5002 - DIAMETER_UNKNOWN_SESSION_ID",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diamResultCodeStatsResultCodeOut{diamResultCodeStatsResultCode=\"5002\", subdomain=~\"$subdomain\"}[5m])"
      }
     ]
    },
    {
     "title": "5030 - DIAMETER_USER_UNKNOWN",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diamResultCodeStatsResultCodeOut{diamResultCodeStatsResultCode=\"5030\", subdomain=~\"$subdomain\"}[5m])",
       "legendFormat": "{{diamResultCodeStatsApplicationId}} - {{diamResultCodeStatsCmdCode}} - {{diamResultCodeStatsResultCode}}"
      }
     ]
    },
    {
     "title": "4010 - DIAMETER_END_USER_SERVICE_DENIED",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diamResultCodeStatsResultCodeOut{diamResultCodeStatsResultCode=\"4010\", subdomain=~\"$subdomain\"}[5m])",
       "legendFormat": "{{diamResultCodeStatsApplicationId}} - {{diamResultCodeStatsCmdCode}} - {{diamResultCodeStatsResultCode}}"
      }
     ]
    }
   ]
  }
 ]
}