{
 "title": "1   Matrixx Summary",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "VISIBLE MATRIXX Eye On Glass", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Engine1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(sysPeerClusterClusterState{instance=~\"proc-s1.*\", sysPeerClusterClusterId=\"1\",sysPeerClusterEngineId=\"1\"})"
    }
   ]
  },
  {
   "title": "Engine2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(sysPeerClusterClusterState{instance=~\"proc-s1.*\", sysPeerClusterClusterId=\"1\",sysPeerClusterEngineId=\"2\"})"
    }
   ]
  },
  {
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sysClusterMemberMgmtIpAddress{instance=~\"proc-s1e1.*\"} - 0 "
    },
    {
     "expr": "sysPeerClusterClusterState{ instance=~\"proc-s1e1.*\", sysPeerClusterClusterId=\"1\", sysPeerClusterEngineId=\"1\"} - 0 "
    },
    {
     "expr": "sysClusterMemberNodeState{instance=~\"proc-s1e1.*\"} - 0"
    },
    {
     "expr": "sysClusterMemberNodeId{instance=~\"proc-s1e1.\"} - 0"
    }
   ]
  },
  {
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "sysClusterMemberMgmtIpAddress{instance=~\"publ-s1e1.*\"} - 0 "
    },
    {
     "expr": "sysPeerClusterClusterState{ instance=~\"publ-s1e1.*\", sysPeerClusterClusterId=\"2\", sysPeerClusterEngineId=\"1\"} - 0 "
    },
    {
     "expr": "sysClusterMemberNodeState{instance=~\"publ-s1e1.*\"} - 0"
    },
    {
     "expr": "sysClusterMemberNodeId{instance=~\"publ-s1e1.\"} - 0"
    }
   ]
  },
  {
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sysClusterMemberMgmtIpAddress{instance=~\"proc-s1e2.*\"} - 0 "
    },
    {
     "expr": "sysPeerClusterClusterState{ instance=~\"proc-s1e2.*\", sysPeerClusterClusterId=\"1\", sysPeerClusterEngineId=\"2\"} - 0 "
    },
    {
     "expr": "sysClusterMemberNodeState{instance=~\"proc-s1e2.*\"} - 0"
    },
    {
     "expr": "sysClusterMemberNodeId{instance=~\"proc-s1e2.*\"} - 0"
    }
   ]
  },
  {
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "sysClusterMemberMgmtIpAddress{instance=~\"publ-s1e2.*\"} - 0 "
    },
    {
     "expr": "sysPeerClusterClusterState{ instance=~\"publ-s1e2.*\", sysPeerClusterClusterId=\"2\", sysPeerClusterEngineId=\"2\"} - 0 "
    },
    {
     "expr": "sysClusterMemberNodeState{instance=~\"publ-s1e2.*\"} - 0"
    },
    {
     "expr": "sysClusterMemberNodeId{instance=~\"publ-s1e2.*\"} - 0"
    }
   ]
  },
  {
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "tfcCfgVipAddress{instance=~\"tralb.*\"} - 0"
    },
    {
     "expr": "sysTraPeerNodeState{instance=~\"tralb.*\"} - 0 "
    },
    {
     "expr": "sysTraNodeState{instance=~\"tralb.*\"} - 0"
    }
   ]
  },
  {
   "title": "TRA- Disaster Recovery",
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "tfcCfgVipAddress{instance=~\"tra-dr-.*\"} - 0"
    },
    {
     "expr": "sysTraPeerNodeState{instance=~\"tra-dr-.*\"} - 0 "
    },
    {
     "expr": "sysTraNodeState{instance=~\"tra-dr-.*\"} - 0"
    }
   ]
  },
  {
   "title": "Checkpoint",
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "sysClusterMemberMgmtIpAddress{instance=~\"ckpt-.*\"} - 0 "
    },
    {
     "expr": "sysPeerClusterClusterState{instance=~\"ckpt-.*\", sysPeerClusterClusterId=\"3\"} - 0 "
    },
    {
     "expr": "sysClusterMemberNodeState{instance=~\"ckpt-.*\"} - 0"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(statSysInfoPhysicalMemoryFreeMb[24h]) + avg_over_time(statSysInfoPhysicalMemoryCachedMb[24h]) + avg_over_time(statSysInfoPhysicalMemoryBuffersMb[24h])) / avg_over_time(statSysInfoPhysicalMemoryTotalMb[24h])))"
    }
   ]
  },
  {
   "title": "All Matrixx Disk Utilization",
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"shared\"}) - 0"
    },
    {
     "expr": "sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"local\"}) - 0"
    },
    {
     "expr": "sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"shared\"}) + sum without (statSysInfoDiskIdStr) (statSysInfoDiskUsedPct{statSysInfoDiskIdStr=\"local\"})"
    }
   ]
  },
  {
   "title": "Publishing Blades System Memory Pool Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(statSysInfoPhysicalMemoryFreeMb{instance=~\"publ-.*\"}[24h]) + avg_over_time(statSysInfoPhysicalMemoryCachedMb{instance=~\"publ-.*\"}[24h]) + avg_over_time(statSysInfoPhysicalMemoryBuffersMb{instance=~\"publ-.*\"}[24h])) / avg_over_time(statSysInfoPhysicalMemoryTotalMb{instance=~\"publ-.*\"}[24h])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "IMDB Synch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Database Synch",
   "type": "table-old",
   "description": " ",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "txnDatabaseObjectName{instance=~\"proc-s1e1-0.*\",txnDatabaseObjectPoolId=\"5\"} - 0"
    },
    {
     "expr": "sum without (instance) (txnDatabaseObjectCount{instance=~\"proc-s1e1-0.*\", txnDatabaseObjectPoolId=\"5\"}) - 0"
    },
    {
     "expr": "sum without (instance) (txnDatabaseObjectCount{instance=~\"publ-s1e1-0.*\", txnDatabaseObjectPoolId=\"5\"}) - 0"
    },
    {
     "expr": "sum without (instance) (txnDatabaseObjectCount{instance=~\"ckpt-s1e1-0.*\", txnDatabaseObjectPoolId=\"5\"}) - 0"
    }
   ]
  },
  { "title": "MATRIXX Diameter Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "All Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diamResultCodeStatsResultCodeOut[5m])",
     "legendFormat": "{{diamResultCodeStatsApplicationId}} - {{diamResultCodeStatsCmdCode}} - {{diamResultCodeStatsResultCode}}"
    }
   ]
  },
  {
   "title": "5002 - DIAMETER_UNKNOWN_SESSION_ID",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diamResultCodeStatsResultCodeOut{diamResultCodeStatsResultCode=\"5002\"}[5m])"
    }
   ]
  },
  {
   "title": "5030 - DIAMETER_USER_UNKNOWN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diamResultCodeStatsResultCodeOut{diamResultCodeStatsResultCode=\"5030\"}[5m])",
     "legendFormat": "{{diamResultCodeStatsApplicationId}} - {{diamResultCodeStatsCmdCode}} - {{diamResultCodeStatsResultCode}}"
    }
   ]
  },
  {
   "title": "4010 - DIAMETER_END_USER_SERVICE_DENIED",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diamResultCodeStatsResultCodeOut{diamResultCodeStatsResultCode=\"4010\"}[5m])",
     "legendFormat": "{{diamResultCodeStatsApplicationId}} - {{diamResultCodeStatsCmdCode}} - {{diamResultCodeStatsResultCode}}"
    }
   ]
  }
 ]
}