{
 "title": "MATRIXX Engine Performance",
 "description": "Defines SNMP statistics and notifications specific to the MATRIXX Engine.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasoruce", "query": "prometheus" },
   { "name": "Subdomain", "label": "Subdomain", "query": "label_values(subdomain)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(camelStatsChargingSessionStartCount{subdomain=\"$Subdomain\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Transaction Message Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(txnMsgCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Diameter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Diameter Code Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(diamResultCodeStatsResultCodeOut{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{diamResultCodeStatsResultCode}} - {{diamResultCodeStatsApplicationId}} - {{diamResultCodeStatsCmdCode}}"
    }
   ]
  },
  {
   "title": "Common Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diamPduStatsTotalResponsesOut{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"0\"}[2m])",
     "legendFormat": "{{instance}} - {{diamPduStatsCmdCode}}"
    }
   ]
  },
  {
   "title": "Credit Control",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(diamPduStatsTotalResponsesOut{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"4\"}[6m])",
     "legendFormat": "diamPduStatsTotalResponsesOut - {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "rate(diamPduStatsTotalRequestsIn{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"4\"}[6m])",
     "legendFormat": "diamPduStatsTotalRequestsIn - {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "rate(diamPduStatsTotalRespTimeAvg{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"4\"}[6m])",
     "legendFormat": "diamPduStatsTotalRespTimeAvg- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "rate(diamPduStatsCurrentRespTimeAvg{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"4\"}[6m])",
     "legendFormat": "diamPduStatsCurrentRespTimeAvg- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "rate(diamPduStatsCurrentRespTimeMax{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"4\"}[6m])",
     "legendFormat": "diamPduStatsCurrentRespTimeMax- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "rate(diamPduStatsTotalRespTimeMax{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"4\"}[6m])",
     "legendFormat": "diamPduStatsTotalRespTimeMax- {{diamPduStatsCmdCode}}"
    }
   ]
  },
  {
   "title": "RX Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(diamPduStatsTotalResponsesOut{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777236\"}[6m])",
     "legendFormat": "diamPduStatsTotalResponsesOut - {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsTotalRequestsIn{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777236\"}[6m])",
     "legendFormat": "diamPduStatsTotalRequestsIn - {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsTotalRespTimeAvg{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777236\"}[6m])",
     "legendFormat": "diamPduStatsTotalRespTimeAvg- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsCurrentRespTimeAvg{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777236\"}[6m])",
     "legendFormat": "diamPduStatsCurrentRespTimeAvg- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsCurrentRespTimeMax{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777236\"}[6m])",
     "legendFormat": "diamPduStatsCurrentRespTimeMax- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsTotalRespTimeMax{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777236\"}[6m])",
     "legendFormat": "diamPduStatsTotalRespTimeMax- {{diamPduStatsCmdCode}}"
    }
   ]
  },
  {
   "title": "SH/DH Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(diamPduStatsTotalResponsesOut{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777217\"}[6m])",
     "legendFormat": "diamPduStatsTotalResponsesOut - {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsTotalRequestsIn{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777217\"}[6m])",
     "legendFormat": "diamPduStatsTotalRequestsIn - {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsTotalRespTimeAvg{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777217\"}[6m])",
     "legendFormat": "diamPduStatsTotalRespTimeAvg- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsCurrentRespTimeAvg{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777217\"}[6m])",
     "legendFormat": "diamPduStatsCurrentRespTimeAvg- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsCurrentRespTimeMax{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777217\"}[6m])",
     "legendFormat": "diamPduStatsCurrentRespTimeMax- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsTotalRespTimeMax{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777217\"}[6m])",
     "legendFormat": "diamPduStatsTotalRespTimeMax- {{diamPduStatsCmdCode}}"
    }
   ]
  },
  {
   "title": "GX Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(diamPduStatsTotalResponsesOut{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777238\"}[6m])",
     "legendFormat": "diamPduStatsTotalResponsesOut - {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsTotalRequestsIn{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777238\"}[6m])",
     "legendFormat": "diamPduStatsTotalRequestsIn - {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsTotalRespTimeAvg{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777238\"}[6m])",
     "legendFormat": "diamPduStatsTotalRespTimeAvg- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsCurrentRespTimeAvg{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777238\"}[6m])",
     "legendFormat": "diamPduStatsCurrentRespTimeAvg- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsCurrentRespTimeMax{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777238\"}[6m])",
     "legendFormat": "diamPduStatsCurrentRespTimeMax- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsTotalRespTimeMax{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777238\"}[6m])",
     "legendFormat": "diamPduStatsTotalRespTimeMax- {{diamPduStatsCmdCode}}"
    }
   ]
  },
  {
   "title": "SY Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(diamPduStatsTotalResponsesOut{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777302\"}[6m])",
     "legendFormat": "diamPduStatsTotalResponsesOut - {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsTotalRequestsIn{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777302\"}[6m])",
     "legendFormat": "diamPduStatsTotalRequestsIn - {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsTotalRespTimeAvg{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777302\"}[6m])",
     "legendFormat": "diamPduStatsTotalRespTimeAvg- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsCurrentRespTimeAvg{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777302\"}[6m])",
     "legendFormat": "diamPduStatsCurrentRespTimeAvg- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsCurrentRespTimeMax{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777302\"}[6m])",
     "legendFormat": "diamPduStatsCurrentRespTimeMax- {{diamPduStatsCmdCode}}"
    },
    {
     "expr": "irate(diamPduStatsTotalRespTimeMax{subdomain=~\"$Subdomain\", instance=~\"$instance\", diamPduStatsApplicationId=\"16777236\"}[6m])",
     "legendFormat": "diamPduStatsTotalRespTimeMax- {{diamPduStatsCmdCode}}"
    }
   ]
  },
  {
   "title": "SMS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "SMS stats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(smsChargingStatsValidInitialDPSmsCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "smsChargingStatsValidInitialDPSmsCount  - {{instance}}"
      },
      {
       "expr": "rate(smsChargingStatsSubmissionCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "smsChargingStatsSubmissionCount  - {{instance}}"
      },
      {
       "expr": "rate(smsChargingStatsReservationCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "smsChargingStatsReservationCount  - {{instance}}"
      },
      {
       "expr": "rate(smsChargingStatsRejectUnknownReasonCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "smsChargingStatsRejectUnknownReasonCount  - {{instance}}"
      },
      {
       "expr": "rate(smsChargingStatsRejectNoCreditCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "smsChargingStatsRejectNoCreditCount  - {{instance}}"
      },
      {
       "expr": "rate(smsChargingStatsImmediateChargeCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "smsChargingStatsImmediateChargeCount  - {{instance}}"
      },
      {
       "expr": "rate(smsChargingStatsFailureCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "smsChargingStatsFailureCount  - {{instance}}"
      },
      {
       "expr": "rate(smsChargingStatsEventReportTimeoutCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "smsChargingStatsEventReportTimeoutCount  - {{instance}}"
      },
      {
       "expr": "rate(smsChargingStatsFailureCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "smsChargingStatsFailureCount  - {{instance}}"
      },
      {
       "expr": "rate(smsChargingStatsBadInitialDPSmsCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "smsChargingStatsBadInitialDPSmsCount  - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Voice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of good IDPs ",
     "type": "bargauge",
     "description": "Number of good IDPs \n",
     "gridPos": { "h": 5, "w": 13, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "rate(voiceChargingStatsValidIdpCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "voiceChargingStatsValidIdpCount"
      }
     ]
    },
    {
     "title": "Number of bad IDPs ",
     "type": "bargauge",
     "description": "voiceChargingStatsBadIdpCount - Number of bad IDPs.\n",
     "gridPos": { "h": 5, "w": 11, "x": 13, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(voiceChargingStatsBadIdpCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "voiceChargingStatsBadIdpCount"
      }
     ]
    },
    {
     "title": "Number of announcements successfully played to the caller. ",
     "type": "gauge",
     "description": "voiceChargingStatsAnnouncementCompleteCount - Number of announcements successfully played to the caller. ",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(voiceChargingStatsAnnouncementCompleteCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "voiceChargingStatsAnnouncementCompleteCount"
      }
     ]
    },
    {
     "title": "Number of attempts to run a VXML script.",
     "type": "gauge",
     "description": "voiceChargingStatsScriptCount- Number of attempts to run a VXML script.\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(voiceChargingStatsScriptCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "voiceChargingStatsScriptCount"
      }
     ]
    },
    {
     "title": "Number of VXML scripts successfully run.",
     "type": "bargauge",
     "description": "voiceChargingStatsScriptCompleteCount - Number of VXML scripts successfully run.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(voiceChargingStatsScriptCompleteCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "voiceChargingStatsScriptCount"
      }
     ]
    },
    {
     "title": "Sessions charging failure applied on receipt of ApplyChargingReport",
     "type": "gauge",
     "description": "voiceChargingStatsCftActionForAcrCount - Number of sessions for which charging failure action was applied on receipt of an ApplyChargingReport. ",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(voiceChargingStatsCftActionForAcrCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "voiceChargingStatsRouteSelectFailureCount"
      }
     ]
    },
    {
     "title": "Voice Session ended due to Route Select Failure",
     "type": "gauge",
     "description": "Number of sessions ended due to route select failure.\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(voiceChargingStatsRouteSelectFailureCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "voiceChargingStatsRouteSelectFailureCount"
      }
     ]
    },
    {
     "title": "Number of sessions timed out waiting for ApplyChargingReport. ",
     "type": "gauge",
     "description": "voiceChargingStatsAcrTimeoutCount\n - Number of sessions timed out waiting for ApplyChargingReport. ",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(voiceChargingStatsAcrTimeoutCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "voiceChargingStatsAcrTimeoutCount"
      }
     ]
    }
   ]
  },
  {
   "title": "Call",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Call Start",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(callStartStatsAttemptCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "callStartStatsAttemptCount - {{instance}}"
      },
      {
       "expr": "rate(callStartStatsBadMsgCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "callStartStatsBadMsgCount  - {{instance}}"
      },
      {
       "expr": "rate(callStartStatsCalledBusyCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "callStartStatsCalledBusyCount  - {{instance}}"
      },
      {
       "expr": "rate(callStartStatsCalledDisconnectCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "callStartStatsCalledDisconnectCount  - {{instance}}"
      },
      {
       "expr": "rate(callStartStatsCalledNoAnswerCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "callStartStatsCalledNoAnswerCount  - {{instance}}"
      },
      {
       "expr": "rate(callStartStatsCallingBusyCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "callStartStatsCallingBusyCount  - {{instance}}"
      },
      {
       "expr": "rate(callStartStatsCallingDisconnectCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "callStartStatsCallingDisconnectCount - {{instance}}"
      },
      {
       "expr": "rate(callStartStatsNotAllowedNoCreditCoun{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "callStartStatsNotAllowedNoCreditCoun  - {{instance}}"
      }
     ]
    },
    {
     "title": "Call Request Count",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "callStartStatsRequestCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Call Success Count",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "callStartStatsSuccessCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Charging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction average by Charging Server",
     "type": "graph",
     "description": "The average number of transactions, per second, processed by the Charging Server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(chrgServerAvgTxnsPerSecond{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current in-progress/pending Transactions",
     "type": "gauge",
     "description": "The current in-progress/pending transaction count. \n",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(txnCurrentTxnCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Sessions Charging Server granted time and applied charging",
     "type": "bargauge",
     "description": "Number of sessions for which charging server granted some time and ApplyCharging was sent",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "voiceChargingStatsFreeCallCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of sessions ended due to no answer. ",
     "type": "gauge",
     "description": "Number of sessions ended due to no answer. ",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(voiceChargingStatsNoAnswerCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Charging Session",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(camelStatsChargingSessionEndCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "camelStatsChargingSessionEndCount - {{instance}}"
      },
      {
       "expr": "rate(camelStatsChargingSessionErrorCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "camelStatsChargingSessionErrorCount - {{instance}}"
      },
      {
       "expr": "rate(camelStatsChargingSessionStartCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])",
       "legendFormat": "camelStatsChargingSessionStartCount - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of ATI TCAP ABORTS received",
     "type": "bargauge",
     "description": "Number of ATI TCAP ABORTS received",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(mapCallOutStatsAnyTimeQueryRoutingErrorCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of ATI ReturnErrors received.",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(mapCallOutStatsAnyTimeQueryErrorCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of ATI Requests sent",
     "type": "gauge",
     "description": "Number of ATI Requests sent",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(mapCallOutStatsAnyTimeQueryRequestCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])) by (instance, job)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of ATI TCAP NOTICES received",
     "type": "gauge",
     "description": "Number of ATI TCAP NOTICEs received",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(mapCallOutStatsAnyTimeQueryRoutingErrorCount{subdomain=~\"$Subdomain\", instance=~\"$instance\"}[5m])) by (instance, job)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true
  }
 ]
}