#Author: OCC
#Date: 18022021
  #Update: 26092023
#Changes: 
#ATT has released DNS 
#Tultitlan: monitoring-prod-alertmanager-tl.mx.att.com
#Sperto: monitoring-prod-alertmanager-qr.mx.att.com
#Delete nginx annotations and added ingressClassName

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: alertmanager
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
  #- host: monitoring-prod-alertmanager-tl.mx.att.com
  - host: monitoring-prod-alertmanager-qr.mx.att.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alertmanager
            port:
              number: 9093
  tls:
  - hosts:
    #- monitoring-prod-alertmanager-tl.mx.att.com
    - monitoring-prod-alertmanager-qr.mx.att.com
    secretName: default-server-secret