apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: vmware-exporter
  template:
    metadata:
      labels:
        app: vmware-exporter
        release: vmware-exporter
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9272"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: vmware-exporter
        # image: mxtltppeharbor.mx.att.com/matrixx_prod01/monitoring/pryorda/vmware_exporter:latest
        image: infra-harbor-paas.attmx-ne.local/matrixx_lab01/pryorda/vmware_exporter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9272
          name: http
        envFrom:
        - configMapRef:
            name: vmware-exporter-config
        - secretRef:
            name: vmware-exporter-password
      imagePullSecrets:
      - name: regcred
      hostAliases:
      - ip: 10.32.177.200
        hostnames:
        - paas-vcsa-01.attmx-ne.local
