apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: exporter-node
  name: exporter-node
  namespace: monitoring
spec:
  # type: ClusterIP
  ports:
  - name: http
    port: 9101
    targetPort: http
  selector:
    k8s-app: exporter-node